### ISSUE TITLE
cli-plugin-e2e-nightwatch breaks builds on 32 bit systems

### ISSUE THREAD

**Issue by lilianaziolek** [vuejs/vue-cli#1010]
### Version
3.0.0-beta.6

### Reproduction link
[http://CannotProvide.NeedsSpecificServer.com](http://CannotProvide.NeedsSpecificServer.com)

### Steps to reproduce
Including cli-plugin-e2e-nightwatch in any build that runs on 32 bit systems breaks the build (in my case it is a dated continuous integration server). This seems to happen because cli-plugin-e2e-nightwatch has a dependency on chromedriver > 2.35, and the last available version of chromedriver that is compatible/available for 32 bit systems is 2.33.

### What is expected?
Ideally the build should run on 32bit systems

### What is actually happening?
Installation of chromedriver fails, thus breaking the build.

---
Is there any specific functionality in chromedriver that cli-plugin-e2e-nightwatch depends on, or is it possible to make it request a lower version of chromedriver, thus allowing me to explicitly set 2.33.2 instead ? At the moment even if my package.json specifies exact 2.33.2, it gets upgraded to (incorrect) latest version, due to dependency from cli-plugin-e2e-nightwatch.

At the moment I'm forced to remove the cli-plugin-e2e-nightwatch plugin altogether, but I hope it's possible to enable it for 32 bit builds.

**Comment by LinusBorg** [comment]
The default nightwatch config requires chrome-driver here: 

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/nightwatch.config.js#L17

you should probably overwrite the like mentioned here: 

https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-e2e-nightwatch#configuration

So you would create your own nightwatch.config.js file and add this:

```javascript
module.exports = {
  selenium: {
    cli_args: {
      'webdriver.chrome.driver': require('chromedriver').path
    }
  },
}
```

That is just the config copied over 1:1, but since now the file is in your poject's root, it should require the chromedriver version which you installed in your project's `/node_modules` (the other version, the dependency of the e2e plugin, should be nested in the plugin's own `/node_modules` sine two different versions would be installed)

**Comment by lilianaziolek** [comment]
Hi @LinusBorg - thanks for the answer, a quick question/doubt - how will this help with the npm dependency? The problem is already on npm install, due to request of https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/package.json for version 2.35. This version cannot be installed on 32bit systems - therefore I don't think it will even reach a stage where the nightwatch config can be used as it will fail resolving dependencies. Or am I missing something? I have to admit I'm no npm expert, but I think dependency resolution comes before nightwatch can kick in?

**Comment by LinusBorg** [comment]
Well, I can't test this since I don't have access to a 32bit system.

Are you saying the installation process breaks / throws an error because `chrome-driver` doesn't build on 32bit systems? Well, then you are probably right, my solution won't work.

If it installs fine, then maybe it can also be required fine, and would only break if actually used (which we don't since we replace it before hat?)

What I am hoping for was that it doesn't break on install/require already, so we can replace it with your specific version through the customization.

If you install your desired version of chrome-driver to your project, your `/node_modules` would look like this:
```
- node_modules
-- chrome-driver *(2.33.2)*
-- @vue
-- -- cli-plugin-e2e
-- -- -- node_modules
-- -- -- -- chrome-driver *(2.5.0)*
```

So while the plugin would require `2.5.0`, you would directly replace that config with yours, which requires `2.33.2`,

To be perfectly honest, if that all doesn't work - I don't think we want to pin an outdated version in the package.json and force people to use that just  to support outdated 32-bit systems.

**Comment by lilianaziolek** [comment]
Yes, chrome driver stopped releasing 32bit versions some time ago, which in turn made the npm wrapper package stop support it too. Basically, at this point when I run npm install the process errors and doesn't go any further than that.
Again, I'm not an npm expert (I'm much more of java dev) but doesn't npm work similarly to mvn or gradle in conflict resolution? I tried enforcing 2.33.2 but it still fails because npm uses the ^2.35 request from cli-plugin-e2e. When I try to npm install, npm insists to go with 2.36 anyway because cli-plugin-e2e requires 2.35 this as a minimum. I think if the dependency there was ^2.33.2 it would be marked as satisfied and not try to install something that cannot be installed.
Now, I understand you don't want to get people to use lower chromedriver version if they can use higher, but surely they still can if the dependency in cli-plugin-e2e says ^2.33.2 - it will install the latest possible, right? Unless, of course, someone (like me) explicitly requests *exactly* 2.33.2 in their package.json - but only in such case (explicit override in json of the main project) it would not use the latest.
Of course feel free to correct me if my understanding of how npm resolves transitive deps is incorrect - but that seemed to be the case from my experience with it so far.

**Comment by sodatea** [comment]
Due to the new versioning strategy of chromedriver - they now align their major version numbers with Chrome, we're expecting a new major version bump every six weeks. And this certainly conflicts with Vue CLI's release cycle.
So, since 4.0.0-alpha.1, chromedriver is a peer dependency of @vue/cli-plugin-e2e-nightwatch, you can install any version you want in your project's package.json.
