### ISSUE TITLE
零时目录权限问题

### ISSUE THREAD

**Issue by soitif** [vuejs/vue-cli#103]
使用
vue init vuejs/vuex my-vuex

会提示

vue-cli · ENOENT: no such file or directory, scandir '/tmp/vue-template-u9gog8x/template'

时不时零时目录权限问题啊，这个怎么修改配置？

**Comment by zigomir** [comment]
[https://github.com/vuejs/vuex](https://github.com/vuejs/vuex) isn't one of vue templates. You can find official ones [here](https://github.com/vuejs-templates). Most popular, `webpack`, would be initialized like so `vue init webpack my-project`.

You get this error because vuex project doesn't even have a `template` directory.

**Comment by soitif** [comment]
o,thanks
