### ISSUE TITLE
Improve error message when using --target lib and the entry file is missing

### ISSUE THREAD

**Issue by fjc0k** [vuejs/vue-cli#1051]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/fjc0k/vue-cli-lib-test](https://github.com/fjc0k/vue-cli-lib-test)

### Steps to reproduce
1. clone
2. yarn
3. yarn run build

### What is expected?
build success

### What is actually happening?
build failed with error: 
```shell
This dependency was not found:

* ~entry in ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

To install it, you can run: npm install --save ~entry
```

---
**notice**: the main.js file is not default

**Comment by markfknight** [comment]
Will there be support for TypeScript (.ts) files in the future?

**Comment by lunsdorf** [comment]
I ran into this issue today (using `@vue/cli-service` in version 4.4.1) and spent quite some time finding the issue and therefor decided to share my findings.

This error can occur if you override the alias config in `vue.config.js`. So instead of doing this:
```js
config.resolve.alias = myAliasConfig
```
you should do something like this:
```js
config.resolve.alias = { ...config.resolve.alias, ...myAliasConfig }
```

This also fixes the same issue when building web-components and the error is something like `~root/src/app.vue?shadow in ./node_modules/@vue/cli-service/lib/commands/build/entry-wc.js`.

I hope this saves some of you a lot of time debugging.
