### ISSUE TITLE
Let the user write the first commit message

### ISSUE THREAD

**Issue by TotomInc** [vuejs/vue-cli#1086]
### What problem does this feature solve?
Change the initial commit message to something more verbose like `init project using vue-cli` or let the user write his first commit message after `vue-cli` have finished to setup everything.

### What does the proposed API look like?
Currently we do not have the choice for a commit message which is by default `init`. It's still possible to amend and rewrite the commit message.

**Comment by dhensche** [comment]
Would you want this to be something that could be captured in a preset configuration (assuming this is task is in reference to cli 3.x), or should it be something captured outside of preset? If it is outside of a preset I would imagine that a new command line arg `--initialCommit` could be provided so that users could skip both sets of prompts by specifying one of the args for choosing a preset along with this new option.

**Comment by TotomInc** [comment]
My initial idea was to add a new command line arg. If the user has not entered the arg, he will have a question to choice his first commit message. It could be saved into a custom preset too.

**Comment by dhensche** [comment]
okay, I'll continue with the implementation I am playing with that keeps it separate from the preset

**Comment by yyx990803** [comment]
Closed via #1116
