### ISSUE TITLE
vue-cli-service does not run in cmd.exe or Powershell

### ISSUE THREAD

**Issue by mrberggg** [vuejs/vue-cli#1119]
### Version
3.0.0-beta.6

### Reproduction link
[https://gist.github.com/mrberggg/18d54d105f8cbfa64bd03cb63f9fdfdf](https://gist.github.com/mrberggg/18d54d105f8cbfa64bd03cb63f9fdfdf)

### Steps to reproduce
Create a new project with vue cli, then navigate to folder.

In bash run `vue-cli-service serve` or `./node_modules/.bin/vue-cli-service serve`. Serve will work properly.

In Powershell/cmd.exe, run `vue-cli-service serve`. Will show the following error:
`'vue-cli-service' is not recognized as an internal or external command`

Try running the service manually by running `.\node_modules\.bin\vue-cli-service serve`. Will pop open Windows' 'How do you want to open this file?' dialog.

### What is expected?
Should run correctly in cmd.exe/Powershell.

### What is actually happening?
Does not run.

**Comment by mrberggg** [comment]
This was an obscure npm edge case, not related to vue-cli. Was using npm in bash on windows to develop, had to test in cmd.exe. Apparently npm only generates .cmd files for Windows when you run npm install from cmd.exe or Powershell. Deleting node_modules and re-installing from cmd.exe fixes this.

**Comment by SteffRainville** [comment]
Similar problem on beta10. had many vue-loader was used without the corresponding plugin error. Fixed it by using CMD instead of PowerShell

**Comment by MTyson** [comment]
Hm, using git bash on windows isn't an obscure edge case.

It's the only way to develop on windows :)

**Comment by s-KaiNet** [comment]
I have installed 3.0 and constantly receive `'vue-cli-service' is not recognized as an internal or external command, operable program or batch file.` in cmd, powershell and bash. Any ideas what's wrong?

**Comment by kmc059000** [comment]
Similar problem for me. Deleting node_modules and reinstalling with `yarn` fixed my problem

**Comment by filipecanatto** [comment]
I have had this problem using windows 7, in my case I run `npm i` and `npm run serve` in Visual Studio embebed terminal. The problem was fixed when I deleted node_modules folder and run `npm i` and `npm run serve` in cmd.

**Comment by zolodeveloper** [comment]
> I have had this problem using windows 7, in my case I run `npm i` and `npm run serve` in Visual Studio embebed terminal. The problem was fixed when I deleted node_modules folder and run `npm i` and `npm run serve` in cmd.

it's so working

**Comment by gitsmaster** [comment]
I have such a problem in Windows 10 64bit
All is due to --global flag...
`npm install --global @vue/cli` or `npm i -g @vue/cli` installs node_modules in global route `C:\Users\Username\AppData\Roaming\npm` 
But `vue-cli-service serve` requires to be loaded in current project module locally

So when installing node modules, it is necessary to put cli without `-g` flag:   `npm i @vue/cli`
And then `npm serve`
Now it's working

**Comment by AdamYoung** [comment]
uninstalled / reinstalled Node/NPM, tried all the recommendations here but nothing is working. Can't get vue CLI to execute npm run serve with or without running cmd/powerShell as Administrator on windows 10 ...

**Comment by thebeekeeper** [comment]
None of the above worked for me, but I think my problem was related to WSL.  Sometimes when I check out a repo using WSL it causes some weird case-sensitivity issues when I try to do things in that directory from cmd.  I checked out my project using git in cmd rather than WSL, and everything started to work as expected.

**Comment by murray-lang** [comment]
I my case I was able to solve the problem by providing a more complete path to vue-cli-service in  package.json. i.e.
`...

"scripts": {
       "serve": "node_modules/.bin/vue-cli-service serve",
       "build": "node_modules/.bin/vue-cli-service build",
       "lint": "node_modules/.bin/vue-cli-service lint"
  }
...`

**Comment by vikas-ukani** [comment]
`npm install --global @vue/cli`

I used this command on my bash terminal 

And, Then I run vue  js app 
using command  `npm start`
And, my terminal shows me and error like, 
> vue-cli-service serve

`'vue-cli-service'` is not recognized as an internal or external command,
operable program or batch file.

What can i do? 

Please, help me,

**Comment by c0d1ng** [comment]
You can try to delete node_modules directory and install again with `npm install`
In my case I copied the `node_modules` directory from a linux installation and apparently windows needs to create its own files.

**Comment by gcleaves** [comment]
Bitdefender (and perhaps other antivirus software) prevents a Windows process from launching a new console because it blocks access to conhost.exe. Thus `npm run serve` was failing silently for me. I do not have the option of changing the way Bitdefender works, so I have worked around the problem by using the cygwin console instead of cmd or Powershell.

**Comment by sypher-samurai** [comment]
try running command prompt as administrator if your account is an administrator account,  and run **npm install --global @vue/cli**. if it still doesn't work run **npm uninstall --global @vue-cli** to uninstall previous versions of Vue. then run **npm install --global @vue/cli** to install Vue

**Comment by leobcgov** [comment]
"npm i" has fixed the issue for me

**Comment by almanalfaruq** [comment]
Still facing the same issue for Windows. I've been trying to delete `node_modules` inside my project, reinstalling again. Create another vue project. The problem still showing up.
At first, I thought because my vue-cli isn't updated yet, but it seems that `npm run <script_name>` will use the global modules instead of the one that installed in my project.

Using absolute path to the vue-cli-service (ex: `.\node_modules\.bin\vue-cli-service serve` via PowerShell) inside the project's `node_modules` solves the issue for me.

**Comment by mhldtna** [comment]
On Windows, if you follow the installation instructions and install @vue/cli using npm installs "-g" option, the vue command is installed in c:\Users\<your username>\AppData\Roaming\npm.  Then when you try to run "vue" the command is not found because it's not in your Windows path.  The easy solution is to add "%APPDATA%\npm" to your path.

**Comment by william-keller** [comment]
Remember to set the NODE_ENV=development and run npm install again

**Comment by astonishqft** [comment]
may be you are in development mode. such as you root dir has an `.env` file.

https://mp.weixin.qq.com/s/VYFtSfBgz_Bolouz21NaEA
