### ISSUE TITLE
vue-cli-service build target wc not honoring name for registering custom element

### ISSUE THREAD

**Issue by ChristianMurphy** [vuejs/vue-cli#1146]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/ChristianMurphy/reproduce-vue-issue](https://github.com/ChristianMurphy/reproduce-vue-issue)

### Steps to reproduce
```
vue create example-component
# select default
cd example-component
npm run build -- --target wc --name example-component
```

### What is expected?
Registered custom element name should match `--name` option

```
window.customElements.define('example-component', vue_wc_wrapper(external__Vue__default.a, src_App))
```

### What is actually happening?
Registered custom element name is `app`

```
window.customElements.define('app', vue_wc_wrapper(external__Vue__default.a, src_App))
```

**Comment by dhensche** [comment]
unless I am mistaken, it looks like I may have encountered a different bug trying to fix this issue. I am unable to build multiple files at once for web components as my entry glob is expanded too early and then only one entry point is passed down to resolveWcConfig.js (instead of the file glob that should be used to find all components I want to build)
