### ISSUE TITLE
Cypress required when building production

### ISSUE THREAD

**Issue by cybercode** [vuejs/vue-cli#1242]
### Version
3.0.0-beta.6

### Reproduction link
[https://gist.github.com/cybercode/49e97783e92b2bdd2710c1e5d9e55508](https://gist.github.com/cybercode/49e97783e92b2bdd2710c1e5d9e55508)

### Steps to reproduce
move build dependencies out of dev. Leave test dependencies in dev

### What is expected?
yarn build should build the dist

### What is actually happening?
error from vue-cli-service due to missing cypress library

---
Esp. deploying from a docker environment, the time required to download cypress, which is not needed for the build is problematic. You should be able to run `vue-cli-service build` without having to install the test tools.

**Comment by AngeloCicero** [comment]
This would be really helpful.

**Comment by yyx990803** [comment]
You probably should have some form of dependency caching based on lockfile hash...

**Comment by cybercode** [comment]
That’s possible. I will test that premise

**Comment by sodatea** [comment]
Moving build tools to `dependencies` does not make sense.

IMHO, the build result should be e2e tested before deploying, so cypress is required in that case.
Otherwise, you can move `@vue/cli-plugin-e2e-cypress` to `optionalDependencies` and use `yarn install --ignore-optional ` / `npm install --no-optional` in docker environments.

**Comment by gjuchault** [comment]
@sodatea I've tried to move `@vue/cli-plugin-e2e-cypress` to `optionalDependencies` and I have the issue described by the author: vue-cli needs all plugins to be installed and thus I have a missing package error.

Could we reopen this issue ?

**Comment by tommoyangn** [comment]
I'd like to +1 this issue. It doesn't make sense to me that we can't separate build tools from test tools. Yes, builds should be tested before deploying, but it doesn't make sense that it's tightly coupled in this way.

In our Jenkins setup where we build our app serially but then test different aspects concurrently this adds a significant amount of time to each build that isn't necessary, since not all of our tests require cypress (We're a PHP shop).

**Comment by sodatea** [comment]
With the newest release, it is now possible to move `@vue/cli-plugin-e2e-cypress` to `optionalDependencies` without causing any errors. So I'll mark this issue as resolved.

**Comment by bpkennedy** [comment]
This doesn't appear to be the case.  I am on @vue/cli-service ^3.3.0 (for all plugins, as well) and I have moved @vue/cli-plugin-e2e-cypress to `optionalDependencies` and I receive a failure in my gitlabCI build when running the default lint task:

```
> vue-cli-service lint

 WARN  Optional dependency @vue/cli-plugin-e2e-cypress is not installed.
 ERROR  Error: Failed to load plugin cypress: Cannot find module 'eslint-plugin-cypress'
Error: Failed to load plugin cypress: Cannot find module 'eslint-plugin-cypress'
```

**Comment by sodatea** [comment]
@bpkennedy 
It is because the tests/e2e sub directory contains its own `.eslintrc.js`, which requires `eslint-plugin-cypress`. Normally, if `@vue/cli-plugin-e2e-cypress` is installed then this package would have already existed.
So in this case, you need to run the lint command with an additional argument:
```
npm run lint -- --ignore-pattern tests/e2e
```

**Comment by bpkennedy** [comment]
Ah awesome, ty
