### ISSUE TITLE
Inspect should accept a --target

### ISSUE THREAD

**Issue by doublemarked** [vuejs/vue-cli#1250]
### Version
3.0.0-beta.9

### Reproduction link
[https://github.com/doublemarked/vue-libconf-issues](https://github.com/doublemarked/vue-libconf-issues)

### Steps to reproduce
`vue inspect`

### What is expected?
`vue inspect` should show webpack configuration that matches that used when building the project, including configuration options like `--target lib` and `--target wc`, both of which inject custom webpack config.

### What is actually happening?
Running `vue inspect` produces inaccurate output because it cannot be instructed to load the lib-specific configuration.

---

**Comment by yyx990803** [comment]
This would require `inspect` to include all other flags including `--name` and `entry`, because the config relies on those values. In addition, both targets uses multiple configs.

In fact, the only difference between the lib/wc config vs. the app version are entry/output options, which are not customizable anyway, so I don't think there is too much value in here considering the complexity in implementing it. I'd be open to a PR if someone wants to work on this though.
