### ISSUE TITLE
Project-based Webpack config is overwritten by lib configuration under --target lib

### ISSUE THREAD

**Issue by doublemarked** [vuejs/vue-cli#1252]
### Version
3.0.0-beta.9

### Reproduction link
[https://github.com/doublemarked/vue-libconf-issues](https://github.com/doublemarked/vue-libconf-issues)

### Steps to reproduce
1. `git clone https://github.com/doublemarked/vue-libconf-issues.git`
2. Observe the `vue.configureWebpack.publicPath` key/val in package.json.
2. `npm install && npm run build`
3. Observe the public path setting is not present in the resulting build artifacts: `grep -R "CLOBB" dist/`

### What is expected?
It should be possible to use Vue webpack configuration placed in package.json or vue.config.js to configure all webpack settings.

### What is actually happening?
Within the build process, webpack customizations (either via `configureWebpack` or `chainWebpack`) are applied before the configuration from resolveLibConfig.js. This makes it not possible to use project-based webpack config to override settings from the lib config.

Note: This also applies to `--target wc`

**Comment by yyx990803** [comment]
Some output options are intentionally applied after user configurations because the user may have a `vue.config.js` with app-specific modifications and still want to use `build --target lib` at the same time for some components.

Closing since after c3d246f and 66bab8c it seems there's no need to tweak them anymore, but let me know if there are other valid use cases that require changing them.
