### ISSUE TITLE
Webpack Subresource Integrity

### ISSUE THREAD

**Issue by ghenry** [vuejs/vue-cli#1274]
### What problem does this feature solve?
Would it be possible to have this as an option for CDN and asset tampering protection, or should it be let for the dev to decide whether they want it?

### What does the proposed API look like?
https://www.npmjs.com/package/webpack-subresource-integrity

**Comment by LinusBorg** [comment]
I woiuld argue that we should leave it to users to take care of this, since it comes with a couple of caveats regarding HTTP and so requires some understanding about the implications of using said feature.

Adding this as a simple "yes I'll use that, seure sounds good" option will result in a lot of people selecting it without knowing about it and subsequently, a lot of confusion when it doesn't work locally, or behind a proxy, or whatever.

**Comment by ghenry** [comment]
Thanks Thorsten.

I was thinking just in the prod build like it recommends, but get your
point. Left in as commented out?

Thanks.

**Comment by yyx990803** [comment]
I think this should really be a userland thing as there are many edge cases that the user would have to evaluate themselves.
