### ISSUE TITLE
this.prop is undefined after upgrade from beta.9 to beta.10

### ISSUE THREAD

**Issue by monsdroid** [vuejs/vue-cli#1308]
### Version
3.0.0-beta.10

### Reproduction link
[https://codesandbox.io/s/62y9086p0r](https://codesandbox.io/s/62y9086p0r)

### Steps to reproduce
```
export default {
mixins: [MixinFactory(this.timeout)],
props: {
            timeout: {
                required: false,
                type: Number,
                default: 6000,
            }
}
}
```
### What is expected?
`this` is defined and refers component

### What is actually happening?
`this` is undefined

---
not sure if its the cli or something else

**Comment by LinusBorg** [comment]
I'm not sure how this should have worked in beta.9, because to the best of my knowledge, it's technically impossible for `this` to be "the component" if you calll it in that place.

in the given code, `this` will be `undefined` in strict mode (which all ES Modules are execued in.

Can you demonstrate a working version of that code?

**Comment by monsdroid** [comment]
Tryed to find an example buuuut the Example i had in mind showd me that this is not possible as well. they use const values.
Thanks for the clarification. Still not sure why it compiles error free right know
