### ISSUE TITLE
 vue-cli · getaddrinfo ENOTFOUND api.github.com api.github.com:443

### ISSUE THREAD

**Issue by ZitQin** [vuejs/vue-cli#148]
需要代理才能上网，

1）使用vue init的时候报错：vue-cli · getaddrinfo ENOTFOUND api.github.com api.github.com:443

2）改到ubuntu 虚拟机上使用，报错：vue-cli · tunneling socket could not be established, cause=write EPROTO 140158953932608:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

在使用git 、npm install 的时候都正常。

请尤大帮忙解决，谢谢！

**Comment by posva** [comment]
Are you using a proxy or something else?
I'm not a network expert but it looks like a man in the middle. If that's not expected you should be worried
Otherwise, there should be some option about strictSSL to set somewhere. I don't know if this has to be set at a proxy's level or while downloading templates

**Comment by ZitQin** [comment]
yes, I used the proxy at office , it has no problem when I user it at home without proxy

**Comment by zigomir** [comment]
@ZitQin closing this issue since it's not related to `vue-cli`.
