### ISSUE TITLE
Command: vue upgrade

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-cli#1507]
Command that should be run inside an existing project with `@vue/cli-service` present.

- Resolve the version to upgrade to.
  - `vue upgrade [patch|minor|major]`: defaults to minor
- If already latest, print message and exit
- Otherwise, confirm via prompt
- Find `@vue/cli-service` plus all packages in `package.json` that starts with `@vue/cli-plugin-`, and bump them to the target upgrade version
- Run `installDeps` - infer package manager from lockfile, if no lockfile, infer from `.vuerc`, otherwise infer using `hasYarn()`
- Print changelog of upgraded versions

**Comment by Akryum** [comment]
What about `upgrade` hooks similar to the `Generator` API?

**Comment by TheMushrr00m** [comment]
Hey there!
Is anyone working on this? I want to try to contribute with this project.

**Comment by LinusBorg** [comment]
@TheMushrr00m Nobody is working on it, feel free to go ahead! Thanks!

**Comment by pksunkara** [comment]
@beardedpayton Can help you if you need any. But we definitely need to think about how other plugins like to handle upgrading. What happens when a plugin which has been added want to change something in the project in a future version? Does it need to reply on `vue invoke vue-cli-plugin-x`? Or can we add a command `vue upgrade vue-cli-plugin-x`?

**Comment by mario-d-s** [comment]
It would definitely be awesome if plugins can handle upgrade scenarios, I hope that is kept in mind!

So far with each RC of Vue CLI I've `vue invoke`'d each plugin to see what it does differently and manually merge in the changes (e.g. `vue-cli-plugin-unit-jest` fixed the test match regex between `rc.3` and `rc.5`).

Imagine if your Vue apps can ride along framework upgrades as smoothly as being generated...

**Comment by NiloCK** [comment]
What is the current workflow for upgrading one's vue-cli packages? Is it safe to do a plain `yarn upgrade vue-cli-service --latest`? I'm currently sitting at 3.0.0-beta.1. What I'm most interested in is getting `vue-cli-plugin-babel` up to speed so that I can hopefully resolve [these sorts](https://github.com/vuejs/vue-loader/issues/1163) of debug / source map issues.

Should I do an upgrade only on `vue-cli-plugin-babel`?
