### ISSUE TITLE
@decorator doesn't work out of box at @vue/cli-service@3.0.0-rc.2

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-cli#1542]
### Version
3.0.0-beta.16

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
update `@vue/cli-service` from `3.0.0-beta.15` to `3.0.0-beta.16`

### What is expected?
work

### What is actually happening?
not work

---
here is the error log
```sh
 ERROR  Failed to compile with 1 errors                     14:32:38

 error  in ./node_modules/beekit.site/components/AppLayout.js

Module parse failed: Unexpected character '@' (15:0)
You may need an appropriate loader to handle this file type.
| `;
|
> @Component({
|   template,
|

 @ ./node_modules/beekit.site/index.js 1:0-47 8:17-26
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.1.27.111:8080/sockjs-
node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by yyx990803** [comment]
Please provide an actual repro.

**Comment by yozman** [comment]
@yyx990803 
https://github.com/bugct/vue/commits/issues/1542

by the way,
could u plz give some advance for https://github.com/vuejs/vue/pull/8312 ?

**Comment by yozman** [comment]
@yyx990803 
still not work at `3.0.0-rc.1`

**Comment by sodatea** [comment]
FYI your reproduction compiles successfully with `3.0.0-rc.3`, though it emits several errors from `eslint-loader`.
It is because ESLint does not natively support experimental ECMAScript language features, you need to config ESLint to use `babel-eslint` as its parser.
[In the case of Vue apps, this option should be placed in `parserOptions` field.](https://github.com/vuejs/eslint-plugin-vue/#what-is-the-use-the-latest-vue-eslint-parser-error)
So to solve this problem, run `npm i -D babel-eslint` and add these lines to `pacakge.json`:

```diff
"eslintConfig": {
    "root": true,
+   "parserOptions": {
+     "parser": "babel-eslint"
+   },
```

Or, you could just use [TypeScript plugin](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript) for decorator support.
