### ISSUE TITLE
transpileDependencies make commonjs modules conflict with webpack module model

### ISSUE THREAD

**Issue by miaulightouch** [vuejs/vue-cli#1568]
### Version
3.0.0-rc.1

### Reproduction link
[https://gitlab.com/MiausF2E/f2e-todos-cli-demo](https://gitlab.com/MiausF2E/f2e-todos-cli-demo)

### Steps to reproduce
1. comment out `process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true` in `babel.config.js`
2. `yarn serve` and take a look in browser console

### What is expected?
no error.

### What is actually happening?
es6 import conflict with commonjs declaration

---
I had discussed in #1248, but it seems no response if I don't file an issue.

**Comment by Akryum** [comment]
You can also use [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies).

**Comment by miaulightouch** [comment]
@Akryum did you read the repo?
I set transpileDependencies in `vue.config.js` already, but I require to set `process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true` in `babel.config.js` to make compilation work.

**Comment by miaulightouch** [comment]
If you had tried the repo, you would see the page is all blank, and console would report error.

what is `You can also use transpileDependencies.`? LOL

**Comment by LinusBorg** [comment]
I'm not sure and can't find a source right now, but I *think* I remember that this is a limitation with babel and/or webpack when using es6 modules - when importing a "native" commonjs module, you *have to* use `require()`, and *can't* use `import`.

Not sure though, will look further into it.

**Comment by miaulightouch** [comment]
`import` or `require` still get the same result.

the problem is I `import` the vue instance as es6 module but `require` commonjs module inside the vue instance.

if I use `require` all vue instance/component, the issue may be resolved, but I don't want to.

**Comment by LinusBorg** [comment]
Ok, ran the production and can verify the behaviour. Not sure why that happens / how to handle it right now.

**Comment by miaulightouch** [comment]
actually, we still can `require` commonjs module inside es6 mobules if `transpileDependencies` is not set.

the problem is babel seems not allowing to mix commonjs with es6 module.

**Comment by yyx990803** [comment]
`VUE_CLI_BABEL_TRANSPILE_MODULES` is an internal flag used by `@vue/babel-preset-app` to make bundles work in Jest or a Node.js environment. It does not guarantee any kind of behavior outside of that use case. What it does is compiling all ES imports into CommonJS, not what you are thinking...

**Comment by miaulightouch** [comment]
um, so, it's resolved?

**Comment by yyx990803** [comment]
It's closed because the original issue is invalid (usage that is not supported), and it didn't clearly explain what you are actually trying to achieve.

**Comment by LinusBorg** [comment]
I came across something similar in a topic on forum.vuejs.org and took another look. I think I found the underlying issue with the help of this issue in the webpack repo:

https://github.com/webpack/webpack/issues/4039

### The problem

* We include a commonjs module from `node_modules` in vue-cli's `transpileDependencies` option
* This module contains code that requires a polyfill
* babel-preset env will inject an `import` statement into that module for the polyfill
* because of that, the module is now in `strict` mode
* ...and in `strict` mode, `exports` is readonly.

So we end up with the error:
```
Cannot assign to read only property 'exports' of object '#<Object>'
```

### Possible Workarounds

#### `useBuiltIns: 'entry'`
One workaround is to switch from `useBuiltIns: 'usage'` (the default for `@vue/babel-preset-app` ) to `useBuiltIns: 'entry'` 
```javascript
module.exports = {
  presets: [
    ['@vue/app', {
      useBuiltIns: 'entry'
    }]
  ],
```

...and add the `import '@babel/polyfill'` that this setting requires to the top of `main.js`. The obvious downside is that we probably end up with unnecessary polyfills in our bundle, increasing its size
Plus, this workaround doesn't prevent all edge cases: If the module in question contains code that will make babel insert a helper from `transform-runtime`  (i.e. helpers for `class` syntax), those will also be injected `import` statements, again switching the module into `strict` mode

#### `modules: 'commonjs'`

> *this one is untested, just read about it*

By default, our babel preset doesn't transpile ES6 modules to commonjs, because webpack >=2 understands those and they enable webpack to do tree shaking.

But if we tell babel to transpile all modules to commonjs, we never enter strict mode, so that should also prevent this error.

### Can we really fix this?

I don't think there's much we can do except maybe document this edge case.

Other ideas?

**Comment by nicoabie** [comment]
@LinusBorg the `import '@babel/polyfill'` would just be needed in order to support older browsers like IE9 and IE10, right? Thanks for the detailed explanation.

**Comment by miaulightouch** [comment]
Actually, you don't need `import '@babel/polyfill'`, [`@vue/app`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app) handle this already. please read `useBuiltIns` section of `preset-env` doc

**Comment by miaulightouch** [comment]
And I finally figure out about this issue.

Sample code:

```js
import esModuleA from 'esModuleA'
const cjsMoudleA = require('cjsModuleA')

export {
  esModuleA,
  cjsModuleB
}
```

And add both to `transpileDependencies`,
webpack would inject `module` object in "harmony way" and `module.exports` would be unavailable to assign new value.

ref: https://github.com/webpack/webpack/blob/master/buildin/harmony-module.js

**Comment by fangbinwei** [comment]
using `transpileDependencies` option, it's  very likely to transpile module which has already been transpiled.
e.g. 
```js
  transpileDependencies: [
    'need_transpile_module'
  ],
```
`need_transpile_module/node_module`  which has already been transpiled will be processed by babel-loader in vue cli, because  RegExp is used to decide if module need to transiple

> https://github.com/vuejs/vue-cli/blob/0bfc4b684fb48cdb27a5b5102023eec7c7cae8c8/packages/%40vue/cli-plugin-babel/index.js#L4

I tried to write complex regexp to solve it. recently I found `sourceType: 'unambiguous'` in babel option can solve this problem
> https://github.com/babel/babel/issues/9187#issuecomment-447704595

Are these related to this issue? @LinusBorg  I think it is necessary to remind people who use  `transpileDependencies` option.

**Comment by lefreet** [comment]
`babel.config.js`

```js
module.exports = {
  presets: [
    ['@vue/app']
  ],
  sourceType: 'unambiguous' // heuristic for every module
}
```

@yyx990803  in my project, it's useful.  [here](https://www.babeljs.cn/docs/options#sourcetype)
