### ISSUE TITLE
[ui] update cli-service package.json

### ISSUE THREAD

**Issue by d62remi** [vuejs/vue-cli#1582]
### Version
3.0.0-rc.2

### Reproduction link
[https://user-images.githubusercontent.com/11924796/41468217-8064972a-70a9-11e8-8451-ad0b05183a71.png](https://user-images.githubusercontent.com/11924796/41468217-8064972a-70a9-11e8-8451-ad0b05183a71.png)

### Steps to reproduce
After update all plugins with cli ui, package.json don't update.

### What is expected?
update of package.json devDependencies

### What is actually happening?
vue/cli-service remains at the previous version

**Comment by Akryum** [comment]
Updating the `package.json` file is not useful since you now have either a `package-lock.json` or `yarn.lock` file which represent the actual versions you use in your project (this one should be updated).
The `package.json` file only contains wanted version ranges. `3.0.0-rc.2` is a valid version for `^3.0.0-rc.1` version range.
