### ISSUE TITLE
Build Target: Server-Rendered planed?

### ISSUE THREAD

**Issue by koljakutschera** [vuejs/vue-cli#1587]
### What problem does this feature solve?
Any plans on Server-Rendered-Apps as build target?

### What does the proposed API look like?
vue-cli-service build --target ssr

**Comment by LinusBorg** [comment]
An SSR build target doesn't make much sense because you can't "build" JUST any Vue app into an SSR app. 

The app has to be written in a certain way in the entry file , which is notably different to the code that the cli currently generates for main.js 

So it would make more sense to implement it as a cli plugin. 

And no, we are currently not planning to write such a plugin, since we feel that `nuxt` and `ream` cover this use case pretty great right now. 

We would welcome community contributions though.
