### ISSUE TITLE
Vui UI create project without any lint

### ISSUE THREAD

**Issue by focussing** [vuejs/vue-cli#1620]
### Version
3.0.0-rc.3

### Reproduction link
[http://www.focussing.nl/shot.png](http://www.focussing.nl/shot.png)

### Steps to reproduce
1) at any folder start "vue ui"
2) step through until last tab "configuration"
3) disable any at "Pick additional lint features"
4) the "Create project" button is disabled, until I choose one "linter / formatter config" from the select box (which I do not want)

### What is expected?
Expected is to be able to create a project without any "linting"

### What is actually happening?
See "steps to reproduce"

**Comment by LinusBorg** [comment]
Your problem is here:

> 2. step through until last tab "configuration"

At that point, you already left the option to use linting active on a previous page. that previous page is where you can deactivate linting - it's preselected so you have to actively de-select it:

![image](https://user-images.githubusercontent.com/1444526/41645975-e2651252-7472-11e8-8dd5-99d541db13b1.png)


The page you are talking about is simply asking you which flavour of linting you want after you already chose to use it.

**Comment by focussing** [comment]
You are absolutely right. Sorry for the inconvenience. The setting was below my sight. Maybe it would be an idea to show the number of currently enabled settings near "Enable features" like "Enable features (xxx currently selected)?
