### ISSUE TITLE
Add non-SPA preset

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#1639]
### What problem does this feature solve?
SPA is a hot topic nowadays, but Vue works great with non-SPA. Adding Vue components to existing sites is still a very common use case for Vue. I think that adding non-SPA support isn't a big deal.

### What does the proposed API look like?
The minimal set of features to implement is:

- disable unique names for assets in dist (`app.js` would be always saved as `app.js`, instead of `app.bad90def.js`)
- add dev server proxy and make the non-SPA URL configurable. 
- add mount point selection to the wizard (that would default to `#app`)

**Comment by diogosalazar** [comment]
Hi @wujekbogdan,

This is how I am getting static file names for my bundles:

````javascript
// vue.config.js
module.exports = {
  chainWebpack: config => {
    if( process.env.NODE_ENV === 'production' ) {
      // Make output CSS file names static
      const extractCSSPlugin = config.plugin('extract-css');
      extractCSSPlugin && extractCSSPlugin.tap(() => [{
        filename: '[name].css',
        chunkFilename: '[name].css'
      }]);
    }
  },
  configureWebpack: {
    // Make output JS file names static
    output: {
      filename: '[name].js',
      chunkFilename: '[name].js'
    }
  }
}
````
Hope this helps.

**Comment by diogosalazar** [comment]
Hi @wujekbogdan, thanks for clarifying.

I would agree that the options provided out-of-the-box seem to be mostly SPA oriented.

As someone who works primarily with legacy projects running on Java/PHP backends the SPA scenario doesn't do it for me either -- and I constantly find myself having to reconfigure vue/webpack projects/boilerplates to generate static assets, loaded by dynamically generated pages (no index.html needed) and mounted to multiple elements on those pages.

Since I am not part of the core Vue team (just another user of the framework) I'd have to defer to someone else.

**Comment by sodatea** [comment]
I think it has been done with the [`pages` option](https://cli.vuejs.org/config/#pages) introduced in 3.0.0-beta.12
