### ISSUE TITLE
Hot module error when reexporting from .vue files

### ISSUE THREAD

**Issue by lazarljubenovic** [vuejs/vue-cli#1676]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/lazarljubenovic/vue-cli-hot-bug](https://github.com/lazarljubenovic/vue-cli-hot-bug) (or [view diff here](https://github.com/lazarljubenovic/vue-cli-hot-bug/commit/1238ab08573a27458b25c984831bf60e2e1c5da4))

### Steps to reproduce
1. Run the app in dev mode (`yarn serve`).

### What is expected?
The app should run in dev mode.

### What is actually happening?
It throws an error which does not allow the developer to work on the app.

```
Uncaught TypeError: Cannot read property 'functional' of undefined
    at makeOptionsHot (index.js?6435:73)
    at Object.exports.createRecord (index.js?6435:47)
    at eval (Functional.vue?91ce:26)
    at Module../src/components/Functional/Functional.vue (app.js:1437)
    at __webpack_require__ (app.js:722)
    at fn (app.js:99)
    at eval (index.ts?81d8:1)
    at Module../src/components/Functional/index.ts (app.js:1461)
    at __webpack_require__ (app.js:722)
    at fn (app.js:99)
```

---
Note that it fails just by registering the component:

```
@Component({
  components: {Functional},
})
```

We do not have to use it in the template to see the effect. If we only `import Functional from './Functional';`, the app still works.

---

I tried quickly fixing it in `node_modules` by changing this problematic line.

```js
// original
function makeOptionsHot(id, options) {
  if (options.functional) {

// quick fix attempt
  if (options && options.functional) {
```

This, however, only propagated the problem further so it's not something fundamental with loading component options.

---

It seems to work when you do `yarn build` to build a production mode and then doing `python2 -m SimpleHTTPServer 80` from the `./dist` folder, so I believe it's a dev-mode-only issue.

**Comment by Akryum** [comment]
I'm not sure to understand why you need a ts file that just reexport the component, why not importing it directly?

**Comment by lazarljubenovic** [comment]
In the full code I am exporting more than one thing. Since `.vue` files can only have one default export, I need a hack around this. 

So I default export the component from `.vue` file, import it in `index.ts` where I also import a bunch of other relevant services to that component.

**Comment by Akryum** [comment]
Why can't you import the Vue file directly and the other services in the other file in two import lines?

**Comment by lazarljubenovic** [comment]
If I understand you correctly, that would produce two import paths, right?

```ts
import Component from 'foo/component.vue'
import {Other, Stuff} from 'foo/services.ts'
```

I'd prefer have under the same path since it's not consumer's responsibility to know inner separation of files.

**Comment by lazarljubenovic** [comment]
Just noticed the label "pending reproduction". Isn't the repository link enough?

**Comment by Akryum** [comment]
Did you read the label tooltip?

**Comment by yyx990803** [comment]
FYI, "re-exporting a component from a ts file" works as intended. The problem is caused by **re-exporting a functional component from within a `*.vue` file**, and I don't understand why you are doing it.

FYI when a functional component is used in another `*.vue` component it hot-reloads the parent component so if you are doing this just for HMR, it's unnecessary.

**Comment by lazarljubenovic** [comment]
I'm doing it because I want to define the component in a .vue file but export more than one thing from it. Since .vue files are allowed to have only a single default export, the only workaround I see is using an index.ts file in a folder for the re-export.

Why I need it in a .vue file? For scoping styles and for general consistency since I define all components that way and I do not see why some would be special just because I want multiple exports from it.

**Comment by yyx990803** [comment]
As I said, re-exporting a vue file from a `index.ts` file is fine and it works as intended.

The problem is re-exporting functional components in a vue file. SFCs assume they are either stateful, or functional via `<template functional>`. Re-exporting a functional component from a vue file is just ceremonial and there's really no point doing it.

**Comment by lazarljubenovic** [comment]
Got it. This was code from back when `template functional` didn't exist, that's why I was confused. Thanks.

**Comment by momo65** [comment]
I'm having the same error, i'm using `JSX` into `*.vue` components, (between the `<script></script>` tags ofc),
and i'm importing some other *.vue components to render into App.vue. I'm using *.vue components because i tried `*.js` component files with JSX, but i couldn't render any of them (i tried a lot of methods & means but when i tried with *.vue files, they were rendered correctly except that error appeared : 
`Cannot read property 'functional' of undefined at makeOptionsHot`)
If you have any ideas how to fix that, or how to use JSX with external components from *.js files.
