### ISSUE TITLE
Create a preset compatible with GoogleBot

### ISSUE THREAD

**Issue by wysman** [vuejs/vue-cli#1711]
### What problem does this feature solve?
Be able to produce a website compatible with GoogleBot without using a node server and SSR.
The website will be able to be hosted on platform like Github Page.

### What does the proposed API look like?
I don't known

**Comment by LinusBorg** [comment]
This can be solved as a community plugin

**Comment by wysman** [comment]
Any tips how to do that ?
I hope vue-cli is made for users with few knowledges about webpack, this kind of answer is really not helpful.

A community user.

**Comment by LinusBorg** [comment]
Your request is only two sentences, so bear with me if I misunderstand but: 

* you want good STO (GoogleBot)
* but you don't  want SSR

That means you want to do pre rendering. 

There's a prerender-spa plugin for webpack which you can try, If you are familiar with webpack etc, you could write a cli-plugin for the prerender-plugin (see our docs in how to  rite cli plugins), but you could just as well directly add it to the cli's webpack config (again, see our docs).


 or you can use nuxt instead of vue-cli which has a `generate` command to pre-render your app. 

If you have further questions, use the dedicated forum or chat to ask for help.
