### ISSUE TITLE
css.extract config setting is not honored in development mode

### ISSUE THREAD

**Issue by rdsn** [vuejs/vue-cli#1801]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/rdsn/almost-default-vue-3-setup](https://github.com/rdsn/almost-default-vue-3-setup)

### Steps to reproduce
using 3.0.0-rc.3
1. vue create projectname
2. selected options:
```
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Cypress
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```
3. create a vue.config.js file in the root directory with the following content:
```
// vue.config.js
module.exports = {
  css: {
    extract: true
  }
}
```
4. npm run serve 
5. inspect the page source

### What is expected?
css is included as a file

### What is actually happening?
css is included in style tags like with css.extract: false

---
window 10 x64,
node v8.11.2

**Comment by Akryum** [comment]
As far as I known this is the intended behavior. https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/css.js#L25

**Comment by LinusBorg** [comment]
While running a dev-server, this is required so Hot reloading of styles works, so I *think* this was intended.

**Comment by mcacek** [comment]
Is this a bug or intended functionality?

**Comment by LinusBorg** [comment]
It's intended since hot reloading doesn't work when extracting css. 

Can you share a use case where extracting css during dev would be worth that drawback?

**Comment by mcacek** [comment]
Perhaps, but I can come up with a workaround. I was unaware of the hot-reloading issue. 

My use case is simply serving client-side assets from webpack dev server and then accessing them from another app running locally that builds pages on the server-side. The references in the SSR page are inconsistent between dev and prod mode if the CSS is not extracted.

**Comment by rdsn** [comment]
In my case I experienced an inconsistent behavior with the following code:

index.html
```
<noscript>
  <strong>We're sorry but seg2project doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
</noscript>
<div id="app">
  <div class="loading-screen">
    <div class="el-loading-spinner"><svg viewBox="25 25 50 50" class="circular"><circle cx="50" cy="50" r="20" fill="none" class="path"></circle></svg><!----></div>
  </div>
</div>
```

app.scss
```
.loading-screen {
  position: fixed;
  z-index: 999999;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  background: #1b226f;
}

.loading-screen .el-loading-spinner .path {
  stroke: #fff;
}
```

When the project is opened in the dev mode the loading screen does not appear (a user sees the blank page) until <style> tags are inserted.
When the project is opened in prod mode (after the build step) - the loading-screen appears right after browser parses closing tag of the .loading-screen element, i.e. a lot faster.

If this setting disables hot-reloading then I could definitely live with that minor inconsistency, but docs should be more clear about this behavior in my opinion.

**Comment by Kshatra** [comment]
Here's a generic case where we need CSS extracted in development mode: ANY proprientary patform (any SAAS for example) where dev team does not have full controll over the environment. And there are lots of them. In my case it's Salesforce - just old Rhino engine scripts as backend controlles - no hot reloading, no nice/fancy Node.js BD stuff- nothing at all. And in this case extracting CSS on dev is infact a benefit because, if i'm working only on page styling, i can use chrome plugin like "reload CSS" to re-apply updated CSS without refreshing the page compleytely and loosing the state of opened dialogs etc. This is only one specific expample, but there are many others.

**Comment by LinusBorg** [comment]
> no hot reloading, no nice/fancy Node.js BD stuff- nothing at all.

In those cases, why run development mode at all? if there's no hot reloading (and presumably no place for a dev server), what do can you use it for?

There's still `build --watch` ...

**Comment by Kshatra** [comment]
But even if i run `build --watch` without explicitly setting the mode i'm still not getting css extracted. It seems related to the **NODE_ENV** set to **development** on my local machine (where the build is made). And that forces **vue-cli-service** to build in **development** mode and omit css extraction. I surely can override NODE_ENV before runnig **vue-cli-service** with some tool like **cross-env**, but it feels like a trick because NODE_ENV looses it's inilial meaning in this case.

**Comment by LinusBorg** [comment]
It's not a trick. If you want your app to behave like a production app (extract css, no HMR, create files on disk, etc. pp.), set NODE_ENV accordingly. 

IF you have different env variables for this situation and the real production mode, then create a sparate mode & env file for that

https://cli.vuejs.org/guide/mode-and-env.html
