### ISSUE TITLE
vue inspect returns "Failed to locate @vue/cli-service." (fails to find global @vue/cli-service on Windows)

### ISSUE THREAD

**Issue by folmert** [vuejs/vue-cli#1805]
### Version
3.0.0-rc.3

### Reproduction link
[https://cli.vuejs.org/guide/prototyping.html](https://cli.vuejs.org/guide/prototyping.html)

### Steps to reproduce
Just run `vue inspect` in the project directory.

### What is expected?
It should return the config in the command line output.

### What is actually happening?
Returns ` ERROR  Failed to locate @vue/cli-service. Make sure you are in the right directory.`
Also didn't work when I've explicitly installed @vue/cli-service globally (`yarn global add @vue/cli-service`)

**It did work however when I installed @vue/cli-service locally** (`yarn add @vue/cli-service`), but for my colleague who's using Mac it's working out of the box (without having to install cli-service locally). Perhaps it can be fixed on vue-cli side to find global cli-service? Maybe it's some path issue?

---
Node version: 10.6.0.  
OS: Windows 10.  
Command line: Cmder, cmd (with admin rights).

**Comment by sodatea** [comment]
The error is raised here:
https://github.com/vuejs/vue-cli/blob/fd1c0d5b8ac6c571c82c67b5b9346f1eea6d1ea1/packages/%40vue/cli/lib/inspect.js#L9-L15
I think your colleague might have accidentally installed @vue/cli-service in an ancestor directory.

**Comment by biapar** [comment]
I've the same problem when copy the project folder from Mac to Windows.

**Comment by yyx990803** [comment]
I assume you are running `vue inspect` in a rapid prototyping project with no local deps - and this is expected because `vue inspect` is just an alias to `vue-cli-service inspect` and requires a locally installed `@vue/cli-service`.

We can try to make `vue inspect` work for the prototyping mode but I don't really see much value in this - in prototyping mode you can't tweak the webpack config anyway.
