### ISSUE TITLE
Partially doesn't work with launched Kaspersky Small Office Security

### ISSUE THREAD

**Issue by Gargo** [vuejs/vue-cli#1861]
### Version
3.0.0-rc.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Before steps - install and run Kaspersky Small Office Security
run:
vue init webpack vue-router

### What is expected?
project template is generated

### What is actually happening?
Error:
vue-cli · Failed to download repo vuejs-templates/webpack: self signed certificate in certificate chain

---
If these apps have conflicts then there should be a way for example how to add vue to antivirus exclusions but it is not obvious

**Comment by LinusBorg** [comment]
I'm sorry that your some software installed on your system is making usage of vue-cli harder.

However, we can't be expected to provide assistance to configure any of the hundreds of combinations of operating systems, anti-virus software, firewall software and whatever else could conflict with vue-cli.

This project is run voluntarily by people, mostly in their spare time, so support like this cannot and will not be provided in the documentation of this project. 

We recommend to ask on stack overflow or forum.vuejs.org

**Comment by Gargo** [comment]
@LinusBorg my argument against is what does `vue init` actually do that it requires root access? It should download and generate files.

If you need my configuration then ok - give me alist of characteristics I need to specify

**Comment by LinusBorg** [comment]
> my argument against is what does vue init actually do that it requires root access?
Your original report didn't mention anything about root access, neither does the error message you shared.

Please don't expect me to read your mind.

Feel free to open an issue with a proper error report if you think this is indeed a bug in vue-cli.

To me it seems like either your antivirus or some corporate proxy mess with your SSL encryption, which is why the connection fails.

> If you need my configuration then ok - give me alist of characteristics I need to specify

I won't debug your system environment for you. I'm not an expert on operating systems, especially not for windows, and even if I were, this is a pretty intense task and totally out of scope of this repository
