### ISSUE TITLE
`npm run build` error:Path must be a string. Received undefined

### ISSUE THREAD

**Issue by libertyAlone** [vuejs/vue-cli#187]
I created my own template project based on the offcial webpack template, but I used webpack2 beta.25 version, I changed some conf to adapt to webpack2's new APIs,but I found when I run `npm run build`,the console will output error Path must be a string. Received undefined, I doubt that the code
`
return loader + (options.sourceMap ? extraParamChar + 'sourceMap' : '')
`
in the webpack.prod.conf.js leaded to the error if the param 'sourceMap' existed such as returning string like css-loader?sourcMap or sth else. I did not really find solutions to it, can someone help me? thx~ 
My template github repo is [vw2-tpl](https://github.com/libertyAlone/vw2-tpl)

**Comment by LinusBorg** [comment]
Hello @libertyAlone 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
