### ISSUE TITLE
npm run serve fails after setting App Name for PWA using vue ui

### ISSUE THREAD

**Issue by amxmln** [vuejs/vue-cli#1890]
### Version
3.0.0-rc.5

### Reproduction link
[https://no.link](https://no.link)

### Steps to reproduce
1. Create a new project using vue ui
2. Use manual configuration and enable PWA support
3. Set an App-Name in the PWA configuration section
4. Try to run serve

### What is expected?
The project starts up and is served with HMR.

### What is actually happening?
Vue CLI exits with an error code of 1
Running `npm run serve` in the console outputs the following:

 `Invalid options in vue.config.js: "org" is not allowed`

---
I also noticed that the App Name input is empty every time that section of the configuration is opened.

**Comment by tgoyer** [comment]
I am having the same issue.  When you set the PWA app name, it adds the following chunk to the `vue.config.json` file:

`
org: {
    vue: {
        pwa: {
            name: 'My-Client-Name'
        }
    }
}
`
Removing that section fixes the build.

**Comment by BigWillie** [comment]
I'm having the same issue too... How would I set the app name without it?

**Comment by Akryum** [comment]
See https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa#vuecli-plugin-pwa

**Comment by rowild** [comment]
@Akryum I do not understand you response: The link you posted leads to the documentation, not a solution to the problem? Could you clarify, please? What is the actual status on this? Is there an open issue (because all duplicates are closed, too)? Thank you!

I am having the same problem. I did remove the `org:` and `vue:` keys, so that the resulting config starts at `pwa:`, sth like this:
```
module.exports = {
  assetsDir: undefined,
  css: {
    sourceMap: true,
    modules: true
  },
  pwa: {
    name: 'JVdS'
  },
[...]
}
``` 
That works.

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/43247103-fcdffaae-90b3-11e8-9e28-f150865da50e.png)
