### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Allenice** [vuejs/vue-cli#1953]
### Version
3.0.0-rc.5

### Node and OS info
node: v8.9.1,  yarn: 1.7.0,  mac os 13.4

### Steps to reproduce
1. Async chunks, like this:
```ts
let routes: RouteConfig[] = [
    {
        name: 'member',
        path: '/member',
        component: () => import('./views/MemberList'),
        meta: {
            
        }
    }
]
```
2.  Build as lib
```bash
vue-cli-service build --target lib --name index src/lib.ts
```

### What is expected?
No error.

### What is actually happening?
When I use my lib module,  it show me the error:
```
Uncaught TypeError: Cannot read property 'bind' of undefined
```

Throw error in this line:
```js
var jsonpArray = typeof self !== 'undefined' ? self : this["webpackJsonpindex"] = typeof self !== 'undefined' ? self : this["webpackJsonpindex"] || [];
/******/ 	var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);

```

---
My vue.config.js
```js
const path = require('path')
const APP_ENV = process.env.APP_ENV
const isLib = APP_ENV === 'lib'

module.exports = {
    outputDir: isLib ? 'lib': 'dist',
    devServer: {
    },

    css: {
        extract: !isLib,
        loaderOptions: {
            // postcss: {}
        }
    },

    configureWebpack: config => {
        if (isLib) {
            return {
                output: {
                    chunkFilename: 'chunks/[name]-[hash:8].js'
                },
                externals: isLib ? ['vue', 'vue-property-decorator', 'vue-router', '@app/element-ui'] : [],
                plugins: []
            }
        } else {
            return {}
        }
    }
}

```

**Comment by LinusBorg** [comment]
Hi, 

Thanks for the report. we appreachiate that you tried to providedetailed code snippets. However, to reallly analyse your issue, we need runnable code, e.g. from a github repository.

You didn't share, for example, 

* the options you chose to create the project, 
* the component raising this error
* the `tsconfig.js` file (I could **guess** you are using typescript from that one annotation in your code and some included externals)

Now instead of copy&pasting these as well, please create a small github repository sharing a runnable project for us to clone and analyse.

**Comment by Allenice** [comment]
When I upgraded to `rc6`, this problem did not appear.
