### ISSUE TITLE
--name must contain a hyphen when building a single web component.

### ISSUE THREAD

**Issue by crazyNoah** [vuejs/vue-cli#2024]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。
build with component methods always come out this bug.
using vue-cli 3.0+ 
build with vue ui

**Comment by bivainis** [comment]
In case someone stumbles on this, the error is received when Vue CLI assumes you're building a single file component, and thus requires you to hyphenate component name:
### Bad
`npx vue-cli-service build --target wc --name mycomponent './src/components/Button.vue'`

### Good
`npx vue-cli-service build --target wc --name my-component './src/components/Button.vue'`

Personally, I was receiving this error when I forgot to wrap my `[entry]` path in quotes (which was not that apparent when the command was in `package.json` scripts), when creating a bundle that registers multiple components. Which confused me, because I was sure I don't need to hyphenate the name in this case. But what probably happened was that vue-cli discared entry value as invalid and then just took first `.vue` file from `components` dir as entry, thus assuming it was supposed to be a single file component.

### Error (notice missing quotes)
`npx vue-cli-service build --target wc --name companyname ./src/components/*.vue`

### Success
`npx vue-cli-service build --target wc --name companyname './src/components/*.vue'`
