### ISSUE TITLE
cli-plugin-e2e-cypress doesn't define cypress as peerDependency

### ISSUE THREAD

**Issue by caugner** [vuejs/vue-cli#2026]
### Version
3.0.0-rc.10

### Node and OS info
Node 10.6.0 / yarn 1.7.0 / Windows 10

### Steps to reproduce
```
$ yarn add -D @vue/cli-plugin-e2e-cypress
$ yarn add -D cypress@3.0.2
$ yarn run vue-cli-service test:e2e
```

### What is expected?
cypress 3.0.2 (`node_modules/cypress/bin/cypress`) should be invoked.

### What is actually happening?
cypress 3.0.3 (`node_modules\@vue\cli-plugin-e2e-cypress\node_modules\cypress\bin\cypress`) is invoked.

---
This is a problem for me, because I'm affected by a bug in cypress 3.0.3 (https://github.com/cypress-io/cypress/issues/2252) that makes previously successful tests fail, so I'm unable to upgrade to `@vue/cli-plugin-e2e-cypress@3.0.0-rc.1`0.

**Comment by LinusBorg** [comment]
Adding it as a peer dependency defeats the purpose of externalizing this as a dependency of the plugin so the user doesn't have to install & upgrade it in their own.

I understand your particular situation, but this situation has its source from a bug in cypress, not the fact that we have cypress as a dependency instead of a peerDependency in this plugin. 

In other words: you don't need cypress to be defined as a peerDependency in this plugin - you need a workaround until the cypress bug is fixed. That workaround would be to 

0. not to use use vue-cli-service
1. manually start a dev server with `npm run serve` to test against
2. manually start cypress with any options to

**Comment by caugner** [comment]
Thank you, @LinusBorg.

As a workaround, I have now added `resolutions` to my `package.json`:

```json
{
 "...": "...",
  "resolutions": {
    "cypress": "3.0.2"
  },
 "...": "..."
}
```

**Comment by LinusBorg** [comment]
Nice, that's a yarn feature, right? Didn't think of that, haven't used it so far.

**Comment by caugner** [comment]
> Nice, that's a yarn feature, right? Didn't think of that, haven't used it so far.

I guess it's yarn-specific. Only found out about it earlier when looking for a solution and stumbled upon it in the [Selective version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) section of the yarn docs.
