### ISSUE TITLE
docs: Possible inconsistency in docs for babel?

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vue-cli#2038]
### Version
3.0.0-rc.10

### Node and OS info
yarn 1.7.0

### Steps to reproduce
Open docs:
- https://cli.vuejs.org/config/#transpiledependencies
- https://cli.vuejs.org/config/#babel

### What is expected?
In both places there were no contradictions

### What is actually happening?
In one place dependencies in node_modules ignored, in other included

---
<img width="774" alt="2018-08-02 11 43 03" src="https://user-images.githubusercontent.com/4497128/43573450-698a904c-964a-11e8-9919-bdbbe383f7b8.png">
<img width="766" alt="2018-08-02 11 43 23" src="https://user-images.githubusercontent.com/4497128/43573451-69b1e232-964a-11e8-8911-679aaa33396d.png">

**Comment by LinusBorg** [comment]
This is not a contradition, just a misunderstanding on your part

#### Why is it not a contradiction? 

The second sentence that you highlighted talks about `babel-loader`, and says that *by default*(**!**), it ignores everything in `/node_modules`. You can use `transpileDependencies` to optionally choose to transpile something in that directory, though.

However, the first sentence that you highlighted is about how `babel` (not `babel-loader`) behaves if it transpiles something form `node_modules` (.e.g because babel-loader tells it to do so because of your `transpileDependencies` settings). The point that this section higlights, is that babel will ignore any babel-config files *in `/node_modules` if you yourself use a `babel.config.js` file in your project root. This is recommended because otherwise, babel might try to use presets and plugins that are not preset in your project.
