### ISSUE TITLE
Cannot import certain npm packages when using TypeScript

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#2062]
### Version
3.0.0-rc.10

### Node and OS info
Node 8.10, yarn 1.9.2, macOS 10.13.6

### Steps to reproduce
https://github.com/ffxsam/repro-import-bug

1. Clone repo
2. Run `yarn && yarn serve`
3. See critical error.

### What is expected?
I expect the app to run with no issues.

### What is actually happening?
Error is given: Cannot invoke an expression whose type lacks a call signature. Type 'typeof moment' has no compatible call signatures.

---
Using `import moment from 'moment'` also does not work.

**Comment by ffxsam** [comment]
Some other imports require different syntax now. For instance, in a traditional JS project, this is fine:

```js
import validator from 'validator';
```

In a TS project, it's not:

```
ERROR in /Users/samh/repro-import-bug/src/components/HelloWorld.vue
38:8 Module '"validator"' has no default export.
```

This fix works for validator, but does _not_ work for moment:

```js
import * as validator from 'validator';
```

**Comment by yyx990803** [comment]
This seems to be a bug in TypeScript, because per its [documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html), `allowSyntheticDefaultImports` should be `true` by default when `esModuleInterop` is `true`.

In this case, it only works properly when `allowSyntheticDefaultImports` is explicitly set to `true`.

Note: Vue CLI simply scaffolds a standard usage for upstream deps like webpack and typescript, it doesn't do any magic beyond the `tsconfig.json` in your project. In the future, please try to locate your issues in upstream tools first before opening an issue in Vue CLI.

**Comment by yyx990803** [comment]
Closed via 350f77b9

**Comment by ffxsam** [comment]
Ah, gotcha. Still, glad to see a simple tsconfig.json change in the Vue TS template fixes it!

**Comment by sodatea** [comment]
Just came across [this comment]:(https://github.com/Microsoft/TypeScript/issues/21535#issuecomment-394038322)

> We only consider `esModuleInterop` to imply `allowSyntheticDefaultimports` when the module target is `commonjs`, `amd`, `umd`, or `system`.

So it's a bug in their documentation. 🙁

**Comment by DanielRosenwasser** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript-Handbook/commit/8e974c814d44381ed05a3b6203894e0f9e39d552, and we'll update the website documentation soon. Sorry about all this.

**Comment by ffxsam** [comment]
@DanielRosenwasser Ahh, yes. My `module` prop is set to `esnext`. Thanks!
