### ISSUE TITLE
PWA exit from app

### ISSUE THREAD

**Issue by iamashraful** [vuejs/vue-cli#2064]
### What problem does this feature solve?
While I'm trying to exit from PWA app with my android back button. I found it's requesting the previous page like `history.go(-1)`. I was looking for a solution. Is there any solution with `vue-cli` or anywhere. 

### What does the proposed API look like?
A new API while I call it'll exit the app. To call that API it may need an event. The event can be a double tap on back button event. Whatever you like to make it easy and workable.

**Comment by LinusBorg** [comment]
Hello @iamashraful 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
