### ISSUE TITLE
New template: `Webpack - Server-side rendering`

### ISSUE THREAD

**Issue by imcvampire** [vuejs/vue-cli#209]
Vuejs 2.0 has 1 nice feature is server-side rendering. But setup this feature runs correctly somehow is too pain for newbie. 

So I think it's nice to add a new template support server-side rendering.

**Comment by egoist** [comment]
something like https://github.com/zeit/next.js for Vue.js would look sweet.

**Comment by kasperhelweg** [comment]
You can check out this WIP template if you'd like : 
```
vue init molamil-com/vuejs-ssr-template <project-name>
cd <project-name>
npm install
npm run dev
```

**Comment by jpt** [comment]
@egoist Have you seen https://github.com/nuxt/nuxt.js ? It's been a while since your comment, but Nuxt is exactly what you are describing, and I like what I see! I would love if if there were something official, though. I always assumed vue-cli would expand to something more like Ember and Angular 2 where you can add a route from the command line, etc. But perhaps that is out of the scope of the Vue core.

**Comment by posva** [comment]
@jpt It doesn't need to be official to be good 😉 . Nuxt is a great project, well maintained and actively being worked on. It'd we a waste to create an official fork of it!

**Comment by xpepermint** [comment]
A simple server-side rendering CLI template for Vue.js: https://github.com/xpepermint/vue-cli-template

**Comment by zigomir** [comment]
Looks like Vue v2.2 will get even more SSR goodies and community is [thinking about it](https://github.com/vuejs-templates/webpack/issues/394). Also see this: https://www.youtube.com/watch?v=InOWBvseRYU&feature=youtu.be&t=5386

**Comment by goriunov** [comment]
Hello is there any update about cli template for ssr, i really would like to have full supported webpack template wich would be managed by official vue js team. I think many peaple get stuck in searching for ssr templates. The temlates which exist usually do not have some feachers for example css bundeling or proper minification. And so on ... . Thank you

**Comment by fahrenq** [comment]
Hello everyone!
It's almost been a year after this issue was created. We got pretty ssr guide but still no template.
In [this](https://github.com/vuejs-templates/webpack/issues/394) issue @LinusBorg mentioned there's work on it, but is it?

If no - I could start build template based on [hn](https://github.com/vuejs/vue-hackernews-2.0) example.

@LinusBorg I'm not sure if you're close to vue-cli and its templates, but can you please coordinate future moves in this issue?
