### ISSUE TITLE
Remove plugins

### ISSUE THREAD

**Issue by walterdavalos** [vuejs/vue-cli#2098]
### What problem does this feature solve?
Be able to remove any plugin that was added by the command vue add, for example @vue/pwa.

### What does the proposed API look like?
vue remove <plugin>

**Comment by yyx990803** [comment]
We are not going to implement this because of the complexity of restoring a project to its previous state, especially when the files may have been modified by the user. When you add the plugin, you will get the chance to review the changed files and commit it - you can revert that commit to achieve the equivalent of removing it.
