### ISSUE TITLE
How to use splitChunks webpack system with vue cli 3?

### ISSUE THREAD

**Issue by isaumya** [vuejs/vue-cli#2184]
Hi,
I wanna use the `splitChunk` option of webpack. I've created the `vie.config.js` file and put the following in there:
```javascript
module.exports = {
  configureWebpack: config => {
		if (process.env.NODE_ENV === 'production') {
			config.splitChunks = {
				cacheGroups: {
					node_vendors: {
						test: /[\\/]node_modules[\\/]/,
						chunks: "all",
						priority: 1
					}
				}
			}
		}
  }
}
```
But when I build my app, nothing gets changed. I've also posted in stackoverflow: https://stackoverflow.com/questions/51816020/how-to-break-the-js-files-into-chunks-in-vue-cli-3-with-webpack-performance-obje/
Did not get any help from there as well. Can anyone please reply?

**Comment by KuzMaxOriginal** [comment]
@isaumya You should use `config.optimization.splitChunks`, as mentioned here: https://github.com/neutrinojs/webpack-chain#configuring-optimizations-shorthand-methods

**Comment by isaumya** [comment]
Hi all, I'm using the following code inside `vue.config.js` file and it is working, So, I'm sharing my code here:

```
module.exports = {
  configureWebpack:{
    optimization: {
      splitChunks: {
        minSize: 10000,
        maxSize: 200000,
      }
    }
  }
}
```

Hope this helps.

**Comment by KuzMaxOriginal** [comment]
@isaumya I don't want to bother you, but I feel a strong urge to explain you that in your first piece of code, you absolute ignore the webpack chained system. I see you mixed up `configureWebpack` and `chainWebpack` properties. That's why it doesn't work.

Basically, if you use the first option, you pass an object with properties you want to configure. Just like you did at your last response.

If you want to pass function, you should use the second option, and instead of writing configuration properties, you use special functions documented in `webpack-chain`.

**Comment by allestaire** [comment]
This is not working, it only split the file, but when you tried to load the application, it only displays white/blank page, but seeing on the network tab from console, it does loaded all the assets

**Comment by AMontagu** [comment]
Do someone have the solution to not have the blank page mentioned by @allestaire ?
