### ISSUE TITLE
Building in modern mode with alternative entry leads to failing compiling

### ISSUE THREAD

**Issue by karudo** [vuejs/vue-cli#2258]
### Version
3.0.1

### Reproduction link
[https://github.com/karudo/vue-cli-bug](https://github.com/karudo/vue-cli-bug)

### Node and OS info
Node 10.9.0 / npm 6.2.0 / macos 10.13.6

### Steps to reproduce
npm run build

### What is expected?
Compiled successfully

### What is actually happening?
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                        2:18:11 PM

This relative module was not found:

* ./src/main.js in multi ./src/main.js
 ERROR  Build failed with errors.

---
If I set alternative entry in modern mode I got fail
vue-cli-service build --modern ./src/main2.js

**Comment by sodatea** [comment]
You can use either

```
vue-cli-service build --mode modern ./src/main2.js
```

or 

```
vue-cli-service build ./src/main2.js --modern
```

**Comment by mihirane** [comment]
I faced a similar issue after I updated my `@vue/cli-*` modules and spent hours searching.

The problem is that the wepack.config file generated automatically by the vue-cli has entry: `./src/main.js` for the app but in my project I named the file `./src/app.js`.

**You can either change the filename itself to main.js or change the webpack config through vue.config.js (by reading the vue cli documentation regararding webpack config).**

You can check your webpack.config by using the command vue inspect.

<img width="153" alt="Screenshot 2020-05-30 at 10 35 27 AM" src="https://user-images.githubusercontent.com/65063434/83320140-23d6dd00-a262-11ea-811e-70ca5a077883.png">
