### ISSUE TITLE
Library relative paths not working in vue-cli 3.0.1

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2485]
### Version
3.0.1

### Reproduction link
[https://dumbo.design/test52.zip](https://dumbo.design/test52.zip)
[Live-Demo](https://dumbo.design/test52/demo.html)

### Node and OS info
Node 10.7.0 / npm 6.4.1 / macOS high Sierra

### Steps to reproduce
– download the minimal reproduction
– npm install dependencies
– build a library without modern mode
– open the provided demo.html 

### What is expected?
Correct image paths

### What is actually happening?
Broken image paths (only `img/logo.png`)

---
I needed to inject an app into a legacy site in form of a modal and therefore build a library with vue-cli3, which gets used as a component in a Vue-runtime app inside the legacy site.

This worked pretty well (https://www.telekom.de/zuhause/heimvernetzung – press the magenta button on the stage to see the app we made) – 

Unfortunately in this setup `<img />`-paths do not work in IE11 (img tags are used in step 6 and 7). __Note: css-backgrounds do work in IE11! (The left and right arrows in the ui panel for instance)__

So I wanted to create a simplified version of this setup illustrating the issue – But now I can't get the paths to work in any browser. Neither css-paths nor img-paths. 

I need / want to reference paths like this
```html
<img src="@/assets/logo.png" />
```
```css
.background {
   background: url(~@/assets/background.png);
}
```

And changed the `baseUrl` like this (as described here https://cli.vuejs.org/config/#baseurl):
```js
// vue.config.js
module.exports = {
    baseUrl: "./",
}
```

### My layman prediction:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/1983382/45360137-f69a5500-b5ce-11e8-812a-e1d7ac9ed35a.png">
in the `test52.umd.js` somehow the `__webpack_require__.p` path seems to be empty?

### EDIT:
This may be related to https://github.com/vuejs/vue-cli/issues/2260 – _the live demo is build with the vue-cli-service changes from this commit https://github.com/vuejs/vue-cli/commit/1973e2de2c7d7cebed38e037ccae9331ff849841_ which is why the css background IS working.

**Comment by LinusBorg** [comment]
Thanks for providing such extensive info. 

However I'm not sure I fully understand the problem's effect, probably because we are not aware how you are serving the demo that you show, and because you don't explicitly write what the *expected* path is, in your opinion.

I downloaded your Zip file and opened the demo.html. Everything in there is working, as expected, since all files are "served" relative to the file's location:

```
-- demo.html
-- test52.css
 |-- /img
    |-- logo.png
```
relative to the html file, the logo's `<img>` is at `img/logo.png`
and in the HTML file, we see this:
```html
<img alt="Vue logo" src="img/logo.png">
```
Which is correct. And it displays correctly in my brower when i simply open demo.html in my browser, as expected. The same goes for the css for the background.

You say the logo doesn't display correctly when opening demo.html - i can't reproduce it.

I can however see that the logo is broken in your live demo. But that seems to be related to how/where you serve it:

You serve the demo.html at `/test52` and import the css file from a *subdirectory* (/distLIB) - which is why the background image works (the filepath is still correct, relative to the css file), but since you moved the HTML file one folder up, essentially, the path of `<img>` is no longer correct.

I don't see how this could work, since webpack can't know at built time that you plan on breaking the relative location of the files.

**Comment by katerlouis** [comment]
There's a misunderstanding (poor choice of filenames on my end)
I am not talking about the `demo.html` inside the `distLIB` folder. 

There is another `demo.html` on the same level as the `distLIB` folder. 

My main problem is: 
the library will be included in many scenarios where I don't have control over the developer will put the code providing the library. __My custom__ `demo.html` (in the root of the zip file) is a stand-in for the legacy site. 

What confuses me:
When you insepct the `<img>` tags in the telekom project on Chrome for instance, they look like this:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1983382/45373402-a7b0e780-b5ef-11e8-86d9-65223b952c19.png">

Whereas in IE (and in my minified reproduction...) the paths look like this
```html
<img src="img/icon-summary-wohnraum.svg" />
```

So somewhere in the chain the path gets build to an absolute path, which is exactly what I wanted! 
For the telekom project, this doesn't work in IE11, which is a huge problem and needs to be fixed ASAP.

And what confuses me the most:
I can't get the minified reproduction to create absolute paths at all, although I don't see what I've done differently! I use the same libraries, use babel-polyfill, same vue-cli version, same build settings–

**Comment by LinusBorg** [comment]
> There's a misunderstanding (poor choice of filenames on my end)
> I am not talking about the demo.html inside the distLIB folder.
> There is another demo.html on the same level as the distLIB folder.

Oh, I see. now it all makes sense ^^

Everything else you describe afterwards is indeed confusing, but must depend on the implementation of the actual library on the live site, and since this is to be a complex setup, I can only take guesses.

What i can say is this:  You can of course add absolute paths at *build time* by setting an absolute `baseUrl`, but since you say the code could be placed anywhere, and presumably should not be rebuilt, that's not an option, right?

But with a relative` baseUrl`, the lib itself and the build system of vue-cli could not have produced these absolute paths at build time, since paths are hard-coded as strings into the generated render functions, so you will end up with hard-coded relative paths in your rendered output as well.

So when you break the relationship between where the code is running (the URL of the page that you run it in) and where the assets are located (some other folder) afterwards, these hardcoded paths **will** necessarily break.

What I see in the minified version:
```javascript
Object.prototype.hasOwnProperty.call(t,e)},i.p="",i(i.s="fb15")}({"0009":function(t,e,i){t.exports=i.p+"img/27637_133366_Tkom_Service_Beratung_Wohnung_63254_2020-12-31_eh1zp6_c_scale__w_4047.jpg"}, //...
```
If I interpret this correctly (if!), even in your live code, the path that gets appended to your relative image paths is an empty string: `i.p=""`. You might be able to take a look at the non-minified version to verify.

### So?

Maybe I have misunderstood again, but the way I understand it right now, I have no idea how these absolute paths are generated, Vue surely isn't doing it. which would also hint at why IE doesn't have them: Whatever mechanism is applying them is broken in IE.

I really see no way that vue-cli could produce anything but the output you are seeing, You could add a prop or config object which you could pass the assets URL at *runtime* to dynamically construct these paths during render, but that's something to implement in userland.

I'm happy to assist you with that, but this issue is the wrong place for that. feel free to contact me on forum.vuejs.org or chat.vuejs.org (maybe voicechat there in german ;) ) and we can look into it.
