### ISSUE TITLE
:style="{backgroundImage: 'url('  s.img_url  ')'}" not working

### ISSUE THREAD

**Issue by nymlc** [vuejs/vue-cli#2496]
### Version
3.0.2

### Node and OS info
Node 10.7.0 / yarn 6.2.0 / Mac 10.13.6

### Steps to reproduce
:style="{backgroundImage: 'url('  s.img_url  ')'}" 
not working

### What is expected?
works well

### What is actually happening?
not working

**Comment by sodatea** [comment]
Please provide a reproduction.

**Comment by nymlc** [comment]
@sodatea demo https://github.com/nymlc/problem/blob/master/cli.zip

**Comment by LinusBorg** [comment]
```javascript
{backgroundImage: 'url(' s.img_url ')'}
```

That's not valid JavaScript. 

```javascript
{backgroundImage: 'url(' + s.img_url + ')'}
// or
{backgroundImage: `url('${s.img_url}')`}

```

**Comment by nymlc** [comment]
@LinusBorg you can get the [demo](https://github.com/nymlc/problem/blob/master/cli.zip)

**Comment by LinusBorg** [comment]
```
data() {
    return {
      bg: require('./assets/bg1.png')
    }
  },
```

**Comment by nymlc** [comment]
@LinusBorg Work well, thanks. So what are the causal factors?

**Comment by LinusBorg** [comment]
Well, as far as webpack is concerned, this is just some argbistrary string: `'./assets/bg1.png'`
You have to use require to let webpack know it should treat it as an asset path.

Thids is not necessary when you hardcode the path in the template
```html
<img src="./some/hardcoded/path.png">
``` 
because then vue-loader can turn it into a `require()` for xou during build time.

**Comment by nymlc** [comment]
@LinusBorg Thank you very much for answer
