### ISSUE TITLE
Test and dev builds omit css and image files

### ISSUE THREAD

**Issue by jost-s** [vuejs/vue-cli#2625]
### Version
3.0.4

### Reproduction link
[https://github.com/jost-s/vue-cli3-demo](https://github.com/jost-s/vue-cli3-demo)

### Node and OS info
Node 8.10.0 / npm 6.4.1 / Windows 8.1

### Steps to reproduce
- Clone repository
- Run `.\node_modules\.bin\vue-cli-service build --mode test`
- Check `./dist` folder
- Set NODE_ENV to "test"
- Run `npm run build`
- Check `./dist` folder

### What is expected?
Create a build including all files

### What is actually happening?
Create a build omitting additional images and css files.

---
At first I ran in to this issue because I deployed an app to a test system where the `NODE_ENV` was set to "test". Building resulted in an incomplete dist folder without images and css files, even though the output said "Building for production...".
After trying different combinations of environment variables and webpack modes, it turns out the problem is two-fold:
1. When building in "test" mode, the images and css files are omitted.
2. When setting `NODE_ENV = test`, it looks like production mode is used, yet css and image assets are omitted from the build.

This issue is related to https://github.com/vuejs/vue-cli/issues/2327

**Comment by jost-s** [comment]
@LinusBorg 
Thank you very much for your detailed answer. I understand the intention and behavior now. I had read the docs but didn't quite get it. Now reading them again it's pretty much all there. I will make a suggestion on how to extend it for clarification.

The solution you provide for the build works fine, thanks. I'm using a pipeline to push to the different environments, and I remember I had thought of that solution reading the yellow note on NODE_ENV in the docs, but wasn't happy with it because it doesn't work on Windows and Linux alike. Anyway, it's good enough for now.

What I'm generally wondering is why does NODE_ENV have to match the webpack production mode? The env var will set different URLs or texts or whatever for different environments, whereas the webpack production mode affects the build itself, like which files to include, source maps, pruning and the whole lot. This seems to be not necessarily related to me.

Like in my case, I could want to deploy an app to a dev system or a test system, where the env vars are set accordingly, but the build should be a production build. Would it be awkward to keep NODE_ENV and webpack mode independent?

**Comment by LinusBorg** [comment]
> What I'm generally wondering is why does NODE_ENV have to match the webpack production mode? 

I think this is another misunderstanding. vue-cli's `--mode` is not (just) webpack's `--mode`, it's our own thing.

Webpack's `--mode` does only [a few things](https://webpack.js.org/concepts/mode/) (one of them setting `NODE_ENV` to `development` or `production`, by the way).

*Our* `--mode` does quite a few more things.

* Load environment variables from `.env`, `.env.local`, `.env.${mode}` and `.env.${mode}.local`
* these env files can set `NODE_ENV`
* if they don't, the mode sets `NODE_ENV` to the matching value
* `NODE_ENV` is used to construct the right webpack config for the set value (see [here](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/dev.js) and [here](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/prod.js), for example)
* determine what mode the dev-server is running in (see [here](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js#L33))
* and some other things

So the point is: 
* webpack's `--mode` isn't really important here - it's a nice shortcut when you use webpack bare-bones, but not enough for our purposes
* `NODE_ENV` is central in the process of determining what primary mode your app is runnning in: `development`, `production` or `test`.
* *our* `--mode` sets this `NODE_ENV` and loads other env variables for the mode that is being set. This allows for e.g. staging environments like explained [here](https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode)

> And I don't know if that ties in with that, but if my NODE_ENV is set to "test" and I call vue-cli-service build --mode production, it says "Building for production" but builds for test. That is confusing to me. 

That's because we never overwrite any environment variable that was being passed in from the system running vue-cli-service.

So `--mode` is still `production`, but the NODE_ENV can't be set to `production` because the system has it predefined.

I'm aware that this is maybe not the most straightforward way to handle this, but it's the best way we  found so far that allows for the flexibility we need to support various ways to define env vars and different modes.

**Comment by jost-s** [comment]
Great explanation again, thanks for that. Now I have it, I believe, and enough material to improve the docs :-)

Two more related questions:
> So --mode is still production, but the NODE_ENV can't be set to production because the system has it predefined.

That makes sense, but the resulting build should be a production build, no?! If NODE_ENV is "test" and I run `vue-cli-service build --mode production`, it should be the same as running `NODE_ENV=production vue-cli-service build`. Currently it's a test build though without assets.

And secondly, when I have an actual production build with all assets included, there's nevertheless an output saying "Images and other types of assets omitted.". Why is that?

**Comment by LinusBorg** [comment]
> That makes sense, but the resulting build should be a production build, no?!

No. As I explained, the NODE_ENV value is what actually determines the kind of webpack config you get. And since we *do not overwrite environment variables from the system*, you build run a build with a test config if your system has defined `NODE_ENV=test`.

As to the second question, I believe that's simply referring to the fact that images and such assets are omitted from the list of created assets that's printrd to the console.

**Comment by jost-s** [comment]
Okay, it's all clarified now, thanks a lot for your help!
