### ISSUE TITLE
e2e nightwatch vulnerabilities npm audit fix

### ISSUE THREAD

**Issue by imlinus** [vuejs/vue-cli#2640]
### Version
3.0.4

### Node and OS info
osx, node v10.10.0

### Steps to reproduce
1) Install any package from NPM,
2) You'll get prompted to run `npm audit fix` for 6 vulnerabilities
3) Run npm audit fix
4) Problem still there
5) Run `npm audit fix - f`
6) Still something with vue-cli-plugin-e2e-nightwatch that keeps bugging

### What is expected?
To not have any issues

### What is actually happening?
Nightwatch keeps on yelling it has some problems

---
Well, since I don't event use nightwatch I don't really have a problem with it. But I thought it would be nice to let you know :-)

Cheers guys, you do an amazing job!

**Comment by imlinus** [comment]
![skarmavbild 2018-09-28 kl 15 08 20](https://user-images.githubusercontent.com/2436222/46210207-654a1300-c330-11e8-9d9d-d83a9414b70a.png)

**Comment by LinusBorg** [comment]
Thanks for the report.

Unfortunately we can't do much about this, it's nested depedencies of nightwatch that are affected, and the semver versions of these packages don't allow an update to a secure version.

Fortunately though, since nightwatch isn't generating any user-facing code, and not running any user-provided input, the type of security problem that's reported here - a DOS attack / command injection - isn't really an issue, at least that's how it seems to me.

So we (including you) can reach out to package maintainers and open an issue about this, hoping they adjust the dependency version ranges, but than than that we can't do much.

**Comment by imlinus** [comment]
Thank you for your quick response Linus!
