### ISSUE TITLE
vue-cli: 3.0.4, transpileDependencies requires babel.config.js to be used

### ISSUE THREAD

**Issue by App3x** [vuejs/vue-cli#2673]
### Version
3.0.4

### Node and OS info
yarn 0.21, node v8.9.0, macOs

### Steps to reproduce
`transpileDependencies` was not working until i moved `"presets": ["@vue/app"]` from `.babelrc` to `babel.config.js`

### What is expected?
transpileDependencies works

### What is actually happening?
transpileDependencies not works

**Comment by LinusBorg** [comment]
That's expected. When transpiling node_modules, `.babelrc` can lead to all sorts of problems since nested `.babelrc` files are respected which would look for presets that might not be installed or might not transpile to the target you want your app to transpile to etc.

In other words: You simply have to use `bbel.config.js` - which is Why we switched vue-cli to it sometime in the beta/rc phase for 3.0, so you shouldn't even have a `.babelrc` file.

**Comment by houd1ni** [comment]
@LinusBorg  It was very hard to find this out.

Isn't it better to notice a user somehow that transpileDependencies won't be used when babel's config either in package.json (my case) or in .babelrc.

By the way, both of the cases are very common.

**Comment by LinusBorg** [comment]
3.0 projects are always generated with babel.config.js for this very reason, it's never added to package.json unlike other configs like eslint or jest.


So I don't see how these cases could very "very common" unless users decide to actively break with that.

That being said, it sure doesn't hurt to add a note.

Please open  new issue requesting a docs change or even better, submit a PR.

**Comment by houd1ni** [comment]
@LinusBorg Not exactly, - we have an option while scaffolding between integrating with package.json (seems much more clean to me) and a dedicated config file.

**Comment by LinusBorg** [comment]
> Not exactly, - we have an option while scaffolding between integration with package.json (seems much more clean to me) and a dedicated config file.

Yes. But independent of your choice this always generates babel.config.js.

If it doesn't we have a bug.

**Comment by App3x** [comment]
@LinusBorg i've migrated my project to vue-loader, that's how i got .babelrc

**Comment by LinusBorg** [comment]
I don't follow... How is this related to vue-loader now?

**Comment by App3x** [comment]
> So I don't see how these cases could very "very common" unless users decide to actively break with that.

@LinusBorg im speaking about common scenario to have .babelrc instead of babel.config.js

**Comment by LinusBorg** [comment]
But it's not common in a Vue CLI project, and that's what this issue is about, since the discussion is about a Vue CLI feature (`transpileDependecies`). 

I don't doubt that `.babelrc` is still widely used in a lot of projects that were created when babel was on version 6, but it's not common in Vue CLI projects since the user would have to actively delete the provided config and replace it with a `.babelrc` file.
