### ISSUE TITLE
using UI to update plugins does not make changes to package.json, only to yarn.lock

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-cli#2684]
### Version
3.0.4

### Reproduction link
[https://github.com/yarnpkg/yarn/issues/2042](https://github.com/yarnpkg/yarn/issues/2042)

### Node and OS info
v10.11.0, 6.4.1, 1.10.1, OSX Mojave

### Steps to reproduce
start UI by using vue ui
notice plugin dependencies are not up to date (example 3.0.3, latest is 3.0.4)
select 'update all plugins' from ... menu
update occurs and UI reflects new version
grep yarn.lock or yarn list | grep shows new version
but package.json is not touched at all, still showing old versions 3.0.0-rc.3

### What is expected?
package.json should also be updated and reflect same versions as yarn lock file

### What is actually happening?
package.json is not being updated at all

---
if you execute from command line:
yarn upgrade @vue/cli-service@3.0.4

then it DOES update package.json as well as yarn.lock

so it is possible to update both files. I think this is much better to have these files in sync as package.json provides an easy way to see which versions are installed and is much more readable then the lock files

**Comment by Akryum** [comment]
Well that's not a bug, it's standard `yarn` behavior. Your command upgrades to a specific version, so yarn *has* to update `package.json` to change the version range because `3.0.4` is not the same as `^3.0.0` for example.
When you upgrade normally, for example from `3.0.3` to `3.0.4` with a version range of `^3.0.0` in `package.json`, yarn doesn't need to update `package.json` because `3.0.4` is a valid version for the `^3.0.0` version range.

**Comment by vesper8** [comment]
I see, well right now all my core deps are showing "^3.0.0-rc.3"

It would be nice if there was some way, some option, to have those updated to "^3.0.4" through the UI
