### ISSUE TITLE
Yeoman Vue Generator compared to the vue-cli?

### ISSUE THREAD

**Issue by brombrommert** [vuejs/vue-cli#27]
Hi! First of all good job on Vue.js! I've been using it in some pet projects recently and it's been a blast. Looking forward to using it in a more official capacity :-)

This might be partial ignorance speaking since I have not looked into it in detail, but I was just wondering why the yeoman generator was dropped in favor of the vue-cli? Especially since the vue-cli appears to be a Vue-flavored Yeoman (e.g., templates vs generators).

Thanks in advance!

**Comment by yyx990803** [comment]
The main reason is that vue-cli makes it easier to just fork one of the official templates and create your own tailored template (instead of having to mess with Yeoman's generator API and publish to npm). Imo Yeoman's generator API verbosity/complexity/constraints just outweighs the extra bits of functionality.

The other factor is branding. `vue init` just feels better than `yo vue` ;)
