### ISSUE TITLE
SnoreToast is added to the start menu when notifying on Windows

### ISSUE THREAD

**Issue by evelynhathaway** [vuejs/vue-cli#2720]
### Version
3.0.4

### Node and OS info
Node v9.4.0, npm v5.6.0, Windows 10

### Steps to reproduce
- Install `@vue/cli` on Windows
- Run `vue ui` on a project
- Install/update/etc a dependency in the UI
  - Note that no notification was triggered and that `%APPDATA%\Microsoft\Windows\Start Menu\Programs` now has a SnoreToast shortcut
- Install/update/etc another dependency
  - Note that a notification was triggered successfully

### What is expected?
SnoreToast would not have a shortcut since the user may not like its addition to their start menu without indication of its purpose.

Additionally, the notification should trigger the first time, but I'm guessing this is caused by SnoreToast failing to notify without an app ID in the start menu to use for the notification.

### What is actually happening?
The shortcut is installed without an opt-in, notification fails the first time

---
The UI's notification API uses [`node-notifier`](https://github.com/mikaelbr/node-notifier) which in turn uses [`SnoreToast`](https://github.com/KDE/snoretoast) for native Windows notifications.

[SnoreToast seems to indicate that a program in the start menu is necessary for notifications](https://github.com/KDE/snoretoast/blob/master/README.md), though I can't find anything to back up that it needs to be in the start menu in case SnoreToast can be used from the `node_modules` folder.

If the CLI was an Electron app, the intended use of `node-notifier` would be to use the shortcut for the CLI instead (which would fix also fix the issue with it not firing and it saying the wrong app name when notifying). Since there isn't a shortcut for the CLI, it sounds like a workaround would need to be found to keep the implementation the same.

The issue with it not firing the first time is most likely related to and could be fixed by "installing" the shortcut before the first notification.

**Comment by ananaszjoe** [comment]
I had no idea what it was when I found it in my start menu, so when I ran it and it ran some scripts in a console window that appeared just for a fraction of a second, I suddenly wasn't sure it's not malware...

IMO it shouldn't add a new shortcut, or if it does, and the user starts it directly, it should display a notification that reads something like "This app is used by other apps to display notifications"

**Comment by june07** [comment]
Yeah, def not cool.  Ran across this just now.

**Comment by Riccarr** [comment]
So, umm .... dude, don't know you from a hole in the ground, but, why in the world would you, as you put it ... "no idea what it was when I found it in my start menu, so when I ran" !!! What!?  Why would you click to run some random program that just appears on your computer. Definition of stupidity, man.  Lol ... then you posted that you actually did what you did, just to make sure that you really were stupid, I guess. Dude, smarten up, your making humanity look stupid.

**Comment by ananaszjoe** [comment]
> So, umm .... dude, don't know you from a hole in the ground, but, why in the world would you, as you put it ... "no idea what it was when I found it in my start menu, so when I ran" !!! What!? Why would you click to run some random program that just appears on your computer. Definition of stupidity, man. Lol ... then you posted that you actually did what you did, just to make sure that you really were stupid, I guess. Dude, smarten up, your making humanity look stupid.

Did you just write 5 lines to tell me you think I'm stupid? 😑

**Comment by Riccarr** [comment]
> > So, umm .... dude, don't know you from a hole in the ground, but, why in the world would you, as you put it ... "no idea what it was when I found it in my start menu, so when I ran" !!! What!? Why would you click to run some random program that just appears on your computer. Definition of stupidity, man. Lol ... then you posted that you actually did what you did, just to make sure that you really were stupid, I guess. Dude, smarten up, your making humanity look stupid.
> 
> Did you just write 5 lines to tell me you think I'm stupid? 😑

Your right, that wasn't very nice. YOU SEE ! That's what happens when dumb stuff leaks out! It affects other people. Gawd ... how do I wash this off!

**Comment by dtbenson43** [comment]
> Without a valid shortcut installed in the Start screen or in All Programs, you cannot raise a toast notification from a desktop app.

https://msdn.microsoft.com/en-us/library/windows/desktop/hh802762

**Comment by narration-sd** [comment]
What a mess. But why did this just  suddenly show up to me today???  It's June 2019...

**Comment by jcsston** [comment]
Another vote to remove this. 
`npm install` should not modify my Start Menu -> Programs folder without prompting.

A command-line program should notify the user via the command-line.

**Comment by h454n5** [comment]
Agree with jcsston

**Comment by mariuszwojtkowski** [comment]
I agree, this is outrageous and the shortcut should not be created!

@Riccarr 
There are nice and well educated people talking to each other and there is you, too. You obviously shouldn't be talking...

**Comment by shelbykauth** [comment]
I am semi-okay with the shortcut.  After this issue specifically 
IF AND ONLY IF the user clicks "okay, install".
Like it should open up a standard Windows "Do you want to let this program install stuff on your computer" thing like a normal program.
I nearly had a panic attack.  Especially when I couldn't find it in "Uninstall or change a program" list.

Or call it something other than SnoreToast.  Like NodeNotifier, so I know where the heck it came from.

@Riccarr, while I completely disagree with your tone, you do have a point.
>Why would you click to run some random program?

But to that point, why would you run some random software that is maintained by a community you're not a part of, that can install random shit on your start menu?  AKA: Why would you run any open-source software, including vue, ever?

Because we're programmers!  That's why!  The breadth of our curiosity has no bounds.

Also, I thought I had maybe installed the program along with three others yesterday and hadn't uninstalled it.  So I was trying to see what it was.  I couldn't remember what I had or had not installed.  When the application closed, I was suddenly afraid that it was running large scripts in the background.  And if running the executable by itself popped up a notification about what SnoreToast was, then I would have known what the program was and probably wouldn't have been bothered by it at all.

**Comment by angelicochris** [comment]
Is this ever going to be addressed. Only noticed it because the project creation got stuck on it. Kind of weird to add something like this without telling the user explicitly.

**Comment by instance** [comment]
If anyone ever decides to get around to implementing this, I'd like to add a feature request for the install process to ask where the user would like that shortcut to be created, because it is rather tedious to clean up and reorganize a start menu after every self-important application decides it belongs in the root of the start menu, and then recreates the same shortcut on every single update. I'd much rather have it down in my dev tools sub-menu...

**Comment by geoffh-aurizon** [comment]
+1 fix this.

And the branded SnoreToast notifications that just start coming up on Windows 10 look pretty much like your box has been pwned. WTF?

**Comment by justinemojal** [comment]
![1587989339145690581628](https://user-images.githubusercontent.com/25073775/80370572-fabdd800-88c2-11ea-829a-3393d65b1cd4.jpg)
Snoretoasts says hi. After doing some laravel.( I might have installed it thru composer or npm)

**Comment by jaruzafa** [comment]
+1 to this! Two years and not fixed yet....

**Comment by lehno** [comment]
I thought today I had a virus or something because of this man

**Comment by Shavindra** [comment]
not really happy with random stuff getting installed without informing/consent!!! I am installing vue and cli. It shouldn't have anything to do with random notifications popping up. If anything why not just output the error in command line like others?

**Comment by rahulramsaha** [comment]
Got quite spooked today too when i opened it and a terminal popped up.
And yeah +1 to at least be notified before installing

**Comment by Matrix159** [comment]
Having an application installed via a npm package without any warning or consent is not cool, 2 years and no follow up still?

**Comment by sodatea** [comment]
It's labeled as "contribution welcome".

**Comment by JoelRummel** [comment]
+1, I too found this in my start menu and immediately thought it was malware.

**Comment by jamesperks-om** [comment]
> +1, I too found this in my start menu and immediately thought it was malware.

Same!

**Comment by ccartee** [comment]
just saw this pop up

found exe, deleted, deleted shortcut.  

don't install garbage without my explicit permission to do so.

**Comment by ellis2323** [comment]
Seriously, not sure it's legal in Europe!

**Comment by CoolOppo** [comment]
How is this still not fixed...?

**Comment by PawFV** [comment]
Its easier to uninstall McAffee than this thing... jesus christ.

**Comment by fatihbabacan92** [comment]
I got shocked that I might have malware on my pc. It is very unprofessional to add such a shortcut to start without notifying the user and very bad for Vue's reputation.

**Comment by Legion2** [comment]
Why does nobody open a PR to remove it?

**Comment by FluentCoding** [comment]
Yeah, rly not cool of them ;/ And I thought that it is a malware.

**Comment by sXe79** [comment]
Just installed itself in my Windows menu. NOT cool at all.

**Comment by SaifurRahmanMohsin** [comment]
@Legion2 Read the comments, that's why. Windows 8+ requires the start menu to be populated to have notifications appear. I think the best solution right now would be to make a postuninstall script to remove this start menu entry. Although ideally that code will have to reside in [SnoreToast](https://github.com/KDE/snoretoast) repo. Alternatively, node-notifier could change it's API to allow passing additional config to specify an app ID so it installs using a different app name based on the package using it. And the uninstall code can reside in this repo itself calling that specific app name to be removed from startup entry.

**Comment by tony19** [comment]
The solution is to provide an `appID` in the `notify()` call (resolved in PR #6000).

**Comment by mayanxoni** [comment]
It's been more than 2 years now but still no official solution to this problem. I just closed 3 tabs before coming to this issue.

**Comment by mellester** [comment]
> It's been more than 2 years now but still no official solution to this problem. I just closed 3 tabs before coming to this issue.

Wel the PR fixcing it is only 17 days old so there is a solution just not ofcal yet

**Comment by PSazu** [comment]
Damn I thought it was or something like that :(((

**Comment by PixeldroidOF** [comment]
I thought I downloaded some bloatware or something from installing apps

**Comment by j-a-m-m** [comment]
Same here, thought it was malware or a virus when I found it, I was immediately suspicious of it.

**Comment by ScarVite** [comment]
> 
> 
> Same here, thought it was malware or a virus when I found it, I was immediately suspicious of it.

same

**Comment by jason-guru** [comment]
same

**Comment by s4m5apu3l** [comment]
same
![изображение](https://github.com/user-attachments/assets/dac70534-530c-4eeb-b091-d0f211d4ebeb)

**Comment by noskill24** [comment]
WTF? Why you install applications on my computer without prompting?
