### ISSUE TITLE
Add `--use-cache` option

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-cli#280]
Maybe we can download the repo to `~/.vue-cli/repos` instead of a random temp path so that we can use cached version later. 🤔 

How do you think?

**Comment by kazupon** [comment]
I think it's good idea.  👍

**Comment by posva** [comment]
I think this should just be by default and always check. This would also enable offline usage

**Comment by likun7981** [comment]
Use cache  by default , `--use-remote`  option to download remote repo,  this may be better

**Comment by defcc** [comment]
Good idea.

**Comment by posva** [comment]
@likun7981 I actually think we should always check and add an option for offline like yarn's `--offline` (only works if cached, no remote check). There's also `--prefer-offline` (download if no cache) which I don't think it's necessary since we should always check for the newest version and cache it. If we use the cache by default and make users use the --remote option manually to update, a lot of people will forget. However, if we have a remote first strategy, it'll work out of the box.

we can even add a `vue cache update` to update all templates cached and `vue cache clear`. But I don't think this is necessary since they update automatically

**Comment by likun7981** [comment]
@posva  your idea is nice , but sometimes , I just want to update  the current one which I need .

**Comment by posva** [comment]
@likun7981 That's what I was saying 😄 : `vue init webpack  test` would try to update the cached version of the webpack template while `vue init --offline webpack test` would directly use the cached version

**Comment by likun7981** [comment]
Sorry , that’s my fault 😂 , I just didn't completely understand your meaning.  I understand now.  
I just only saw `vue cache update` to update **all** templates

**Comment by posva** [comment]
@likun7981 😆 No worries. I was just thinking out loud. I think we **shouldn't** add a `vue cache update` command

**Comment by egoist** [comment]
Any thoughts on https://github.com/vuejs/vue-cli/pull/303 ?
