### ISSUE TITLE
vue create: In TS only project spread operator `...` is transpiled to es5, but Object.assign is not

### ISSUE THREAD

**Issue by saintech** [vuejs/vue-cli#2908]
### Version
3.0.5

### Node and OS info
Node 8.11.4 / npm 5.10.0 / Windows 10

### Steps to reproduce
```
$ vue create ojb-assign-issue

Vue CLI v3.0.5
? Please pick a preset: Manually select features
? Check the features needed for your project: TS
? Use class-style component syntax? No
? Use Babel alongside TypeScript for auto-detected polyfills? No
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
```

In `src/main.ts` after imports add following lines:

```
console.log(JSON.stringify({...{hello: 'world'}}));
console.log(JSON.stringify(Object.assign({},{hello: 'world'})));
```

```
$ cd ojb-assign-issue
$ npm run serve
```

### What is expected?
In IE 11 console:

```
...
{"hello":"world"}
{"hello":"world"}
```

### What is actually happening?
`Object.assign` is not be transpiled although there is a working transpillation for spread operator:
```
...
{"hello":"world"}
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
SCRIPT438: Object doesn't support property or method "assign"
eval code (451) (9,1)
```

**Comment by LinusBorg** [comment]
That's how typescript does it. 

`Object.assign` is not transpiled, not even by babel, because that would be too bloated. Instead, this is a language *feature* that has to be reimplemented with a polyfill. While Babel (or rather - it's `-env` preset) can auto-detect and insert required polyfills, Typescript doesn't have this ability.

And since you chose not to use Babel for autodetecting polyfills, providing the proper polyfills is left to you, the typescript user.

You can verify what I say by checking out your example code's transpilation in [Typescript's Playground here](http://www.typescriptlang.org/play/#src=console.log(JSON.stringify(%7B...%7Bhello%3A%20'world'%7D%7D))%3B%0D%0Aconsole.log(JSON.stringify(Object.assign(%7B%7D%2C%7Bhello%3A%20'world'%7D)))%3B)
