### ISSUE TITLE
Prettier does not play well with vue/recommended

### ISSUE THREAD

**Issue by duckness** [vuejs/vue-cli#2920]
### Version
3.1.1

### Reproduction link
[https://github.com/duckness/linttest](https://github.com/duckness/linttest)

### Node and OS info
Node 10.11.0 / yarn 1.12.1 / Windows 10

### Steps to reproduce
1. `vue create` a new app and select the `Eslint + Prettier` option
2. Change `plugin:vue/essential` to either `plugin:vue/recommended` or `plugin:vue/strongly-recommended` in your ESLint config
3. run `yarn lint`

### What is expected?
All lint errors auto-fixed with no error message.

### What is actually happening?
Lint errors cannot be fixed and it will throw an error every time.

**Comment by LinusBorg** [comment]
Might be because of this?

https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/script-indent.md#important-note

**Comment by andylima** [comment]
The way that issue is being handled by Prettier devs (and other issues related to Vue support) is very telling — Prettier is not interested in following any Vue / React / Angular Style Guides that are against its style.

…And its style, as you know, tends to be non-configurable.

Vue ESLint rules are much more useful for us Vue devs than whatever "special" formatting the Prettier people may think is best for us.

…That's why I stopped using Prettier, and suggest you do the same.

For this reason, I suggest Vue CLI to stop using / suggesting eslint-config-prettier by default. This is absolutely NOT the best for Vue devs, especially newcomers to Vue.

**Comment by duckness** [comment]
yes, I have dropped prettier in my project for now

**Comment by sodatea** [comment]
Seems to have been fixed by https://github.com/vuejs/vue-cli/pull/2932

**Comment by visualjerk** [comment]
If someone runs into this issue, try reinstalling @vue/eslint-config-prettier.

```
yarn remove @vue/eslint-config-prettier
yarn add @vue/eslint-config-prettier --dev
```

**Comment by bys1123** [comment]
Wow, this fixed my problem.

**Comment by hvitis** [comment]
Update prettier workspace settings and delete or overwrite your main settings.json that can keep breaking your local linting

**Comment by AchlysLove** [comment]
HI, if you are going to use webstorm with the same setup. Go to the **Preference/Language & Framework/JavaScript/Prettier** section, for "Run for files" input, use "{**/*,*}.{js,ts,jsx,tsx,vue}"(+ vue)
