### ISSUE TITLE
什么现代化的开发体验？用这个就是折磨人？ctrl+s后迟钝的要死，n此修改才自动编译一次

### ISSUE THREAD

**Issue by buuug7** [vuejs/vue-cli#295]
我在win7上，每次修改代码ctrl+s后cli程序根本没反应，n此来回反复修改才自动刷新浏览器，我之前用gulp+browser-sync写代码，一个字非常流畅，着cli怎么写的？折磨死人怎么会有这么多颗星星，你们都脑残么？

**Comment by posva** [comment]
If you actually found a bug, please open new issue.
I couldn't get all of what you said by using the translator (it may be better, looks a bit offensive) so maybe I'm missing something. Make sure to read the [contributions guidelines](https://github.com/vuejs/vue-cli/blob/master/CONTRIBUTING.md)

**Comment by buuug7** [comment]
@posva i ran this in the win7 plateform,my computer hardware configration is very high.when you save your code with the `ctrl+s`,the cli could not auto execute,you need changed some code back and forth several times,then the cli know your code is changed and then run compile scripts,i could not bear this.how is your say this is the moder technique of web developer?why not use the gulp+browser-sync,it was very fluent with this . why build a wheel is not round than  forefathers makes

**Comment by LinusBorg** [comment]
> ,the cli could not auto execute,you need changed some code back and forth several times,then the cli know your code is changed and then run compile scripts

I read this as you having problems with webpack's --watch mode and Hot Module Reloading.

this feature has some issues, for example with files in dropbox folders, or IDEs that don't save to files directly, because those mechanisms screw fith file watchers.

But generally, it works very reliable and 

> why build a wheel is not round than forefathers makes

Well, there are many things webpack can do that gulp can't, or can't as efficiently (e.g. HMR, code splitting ...), and the fact that countless numbers of devs ue it even though it is not easy to learn at first speaks for itself in a way.

> why not use the gulp+browser-sync,it was very fluent with this .

If you feel more comfortable with those tools, then by all means, use those.

**Comment by buuug7** [comment]
@LinusBorg  can you think the webpack can sove the all problem and instead of the gulp?
i think the gulp+webpack is current best solutions,but the future neither of them can suit

**Comment by egoist** [comment]
@posva @LinusBorg you guys are so kind, so patiently answering such rude pointless issue.

**Comment by buuug7** [comment]
@egoist  

You seem to have a prejudice against me

**Comment by buuug7** [comment]
@egoist 

Your avatar betrayed you.

**Comment by LinusBorg** [comment]
@egoist I stopped letting rudeness get to me a long time ago. My life has been more happy since.

@buuug7 You are indeed quite rude. And since this problem has more to do with webpack and less to do with Vue, I think this discussion is no longer productive.
