### ISSUE TITLE
@vue/eslint-config-prettier fails since 4.0.0

### ISSUE THREAD

**Issue by houd1ni** [vuejs/vue-cli#2960]
### Version
3.1.1

### Node and OS info
latest node, latest win10 and MacOS High Sierra.

### Steps to reproduce
Create a project with vue-cli and @vue/eslint-config-prettier@4.0.0 or 4.0.1.
Add vue/max-attributes-per-line rule.

The prettier makes carriage return without tabulation, then linter fails very often with the same error:

```
error: Attribute "icon" should be on a new line (vue/max-attributes-per-line) at src\views\View.vue:33:24:
  31 |         <template slot-scope="{ row }">
  32 |           <router-link :to="{ name: 'name', params: { param: value } }">
> 33 |             <el-button icon="el-icon"
     |                        ^
  34 | size="small" />
  35 |           </router-link>
  36 |         </template>

```

### What is expected?
prettier makes my code pretty.

### What is actually happening?
prettier makes my code ugly.

---
Since 4.0.0. We've checked all other deps.

**Comment by LinusBorg** [comment]
I assume that should be solved by #2932

**Comment by houd1ni** [comment]
@LinusBorg  Thanx! I'll wait for the merge and test again, then close the issue if OK.

**Comment by houd1ni** [comment]
@LinusBorg  I see this is actually merged. How can I install this package from github?

**Comment by houd1ni** [comment]
After hard replacing in node_modules and ```npm i``` there, all works as expected!

**Comment by sodatea** [comment]
1. The PR has already been shipped in @vue/eslint-config-prettier v4.0.1, so you might need to clean your cache.
2. Prettier is incompatible with the rule `vue/max-attributes-per-line`
That's why it's disabled in [eslint-config-prettier/vue](https://github.com/prettier/eslint-config-prettier/blob/152bd7d6582816a493ac0ab619bd8789ac57f280/vue.js#L12)

**Comment by houd1ni** [comment]
@sodatea 
Cache doesn't fix the issue.
So, to fix it, should we disable the rule?
Are there any thoughts about warning if using the rule, if it is the cause?

**Comment by sodatea** [comment]
The prettier config is quite different from other configs, that is, it is used to disable certain rules rather than enabling rules.
So it might be a better practice to always put it at the end of the `extends` array to ensure the rule override has taken effect. For your own custom rules, put them into a separate config file and prepend the path to `extends` in `.eslintrc.js`.
