### ISSUE TITLE
`build --server` for server-side rendering and `build --prerender` for prerendering

### ISSUE THREAD

**Issue by xpepermint** [vuejs/vue-cli#309]
Thanks to @egoist, the new version of this tool `2.8` provides a `build` command which magically serves or compiles your Vue.js project.

It would be super awesome to extend this and add support for `--server` options which would create a bundle for using Vue.js application server-side. I built [vue-builder](https://github.com/xpepermint/vue-builder) for easy building of these bundle files but having something like this as part of `vue-cli` would be even more awesome.

In most cases I need to pre-render my public Vue.js applications using [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin). Adding `--prerender` options would be super awesome :).

**Comment by egoist** [comment]
Why not use @nuxt ?

**Comment by xpepermint** [comment]
@egoist Well, instead of having N different frameworks, `vue-cli` seems a good place to put all the magic ;).

**Comment by egoist** [comment]
SSR is much different from the current `vue build`, maybe you can call it `vue serve`,  Nuxt is doing pretty well in this so it's not likely to add such feature.

Prerender is as simple as adding a webpack plugin and is not frequently used.

**Comment by alidcastano** [comment]
I agree Nuxt is great but if you don't need most of what it offers then it doesn't make sense to let a framework take over your application

i.e. if you're querying data with graphql, you don't really need to split components into pages since everything already happens on a per component basis... 

Found this issue because I'm considering supporting Vue.js in [Rogue](https://github.com/alidcastano/rogue.js). If you find this and are interested, upvote/comment in the the issue so I can know that there's interest https://github.com/alidcastano/rogue.js/issues/70
