### ISSUE TITLE
Downloading template from npm registry

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-cli#311]
Currently something like `vue init webpack` will make vue-cli download git repo `vuejs-template/webpack`, I thought instead we can make it download from npm registry if the template name does not contain `/`. For example `vue init webpack` would install package `vue-template-webpack`, thus everyone can type less to generate from their own template 🤗 just like [sao](https://github.com/egoist/sao)

**Comment by posva** [comment]
But wouldn't that mean we need to publish the templates to the npm registry, making it more complicated?

**Comment by egoist** [comment]
People can still download from git repo if they feel publishing a package a bit complicated.

**Comment by posva** [comment]
Oh right, we only need to publish our templates as packages
But isn't it easier to just pushing to github 😄

**Comment by LinusBorg** [comment]
@posva Sure it's easier for us, but We already see that the continous upgrades an leave people coinfused, because with our github releases its not really clear which feature / depenency is part of the template since when etc.

I think publishing templates via npm would lead to a better maintainability as we would release explicit versions and could also analyse which version users were using when they report a problem.

**Comment by posva** [comment]
Makes sense. I see the interest, people, I know @kazupon does release versions of his templates (I don't know if he publishes them), and has a nice changelog.

**Comment by kazupon** [comment]
In general, I think that we create the templates and use it by oneself, so I don't always think we want to release to npm. Actually, I also don't publish to npm. However, it's rather troublesome to type the long template name everytime.

**Comment by skiano** [comment]
This sounds like a great feature to me :) I have a repo with a bunch of build helpers for a group of related projects, and the idea of separating out a repo just for the cli template (vs just publishing from inside a folder in my build tools repo) seems cumbersome.

**Comment by fcroce** [comment]
I hate to come back on a closed issue, but I have a similar problem:

Our company uses **Verdaccio** and we have a number of packages and now **templates** published there, but "vue init" doesn't seem to offer the option to use a custom mirror and download the template from NPM.

The template is specific for my company, so I can't publish it on `vuejs-template`

The only solution I found so far, (ugly though...), is to git clone and use the template from local with `./`

Is there a way to use a mirror that is not documented, or is it worth a feature in the vue-init project?

Any suggestion is appreciated @egoist , @posva

**Comment by LinusBorg** [comment]
you can install the template from npm and then run `init` with a local path:
```
vue init ../node_nodules/your-templates name-of-project
```

**Comment by fcroce** [comment]
@LinusBorg it's more or less the same as we do now:

```
git clone ...
vue init ./my-template
```
I was curious if there was a better way.

Something like `vue init npm@my-template my-project` would be nice and because it's using NPM we can have a private package manager in `.npmrc`

```
registry = http://verdaccio.on.docker:4873/
```

If it's overkill I guess git clone or using the node_modules folder will do.

Thank you!

**Comment by LinusBorg** [comment]
Yeah we don't intend to change anything about the `init` feature in the foreeable future as we see it as a legacy feature. We focus on the new plugin-base approach of `vue create`
