### ISSUE TITLE
envs shoud be allowed to put  together in on env file to make code cleaner

### ISSUE THREAD

**Issue by JasonZough** [vuejs/vue-cli#3113]
### What problem does this feature solve?
Env files should be allowed to put togather in on file to make codes clean when there are too may env files. 

### .env.json

```
{
  "development": {
      "xxx": "xxx"
  },
  "production": {
      "xxx": "xxx"
  },
  "test": {
      "xxx": "xxx"
  },
  "other": {
      "xxx": "xxx"
  }
}

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by jhechtf** [comment]
While I also understand the frustration, I'll voice my opinion that I don't think this is a good idea. Part of what `.env` files accomplish is to have a layer of configuration for each environment. The reason that you (_should_) only ever see an `.env.example` or an `.env` file with values that obviously dictate a development / local environment are because most of the time companies don't want _everyone_ to have access to their testing/staging/production database connection information (or other sensitive information).

Putting _all_ of that into one file removes that layer. It's possible that someone can still figure out the values in the .env file based on SSH-ing into an instance or server, but that would also mean that that person is trusted enough to _have_ ssh access.

**Comment by sodatea** [comment]
As @jhechtf said, it is not a good idea and we won't add this feature.
