### ISSUE TITLE
inline fonts: Failed to decode downloaded font: data:font/woff2;base64,...

### ISSUE THREAD

**Issue by mbana** [vuejs/vue-cli#3215]
### Version
3.0.5

### Reproduction link
[https://github.com/banaio/vue_js_inline_fonts_bug](https://github.com/banaio/vue_js_inline_fonts_bug)

### Node and OS info
v8.12.0 / 1.10.0 / Mac OS X 10.14.2

### Steps to reproduce

```sh
git clone git@github.com:banaio/vue_js_inline_fonts_bug.git
cd vue_js_inline_fonts_bug
yarn install
yarn serve
open http://localhost:8080/
```

open Developer Tools

### What is expected?
I want to inline all the fonts, so the fonts should be inlined correctly.

Images inline correctly but for some reason fonts do not.

### What is actually happening?
The fonts are not being loaded and when I open Developer Tools, I see the errors below:

```sh
[HMR] Waiting for update signal from WDS...
localhost/:1 Failed to decode downloaded font: data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmb250cy9NZXRyb3BvbGlzLUJvbGQuNmE4MDEyNWUud29mZjIiOw==
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmb250cy9NZXRyb3BvbGlzLUJvbGQuNmE4MDEyNWUud29mZjIiOw==
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmb250cy9NZXRyb3BvbGlzLVJlZ3VsYXIuNGE0MDU3NjIud29mZjIiOw==
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: data:font/woff2;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJmb250cy9NZXRyb3BvbGlzLVJlZ3VsYXIuNGE0MDU3NjIud29mZjIiOw==
localhost/:1 OTS parsing error: invalid version tag
```

---
There is another branch, https://github.com/banaio/vue_js_inline_fonts_bug/tree/working, with the **_working_** version.

If you inspect the difference between master, where it is failing, and the branch in which it is working, https://github.com/banaio/vue_js_inline_fonts_bug/compare/working...master (_**working**_), you will see what the difference. The main difference is this file: https://github.com/banaio/vue_js_inline_fonts_bug/blob/master/vue.config.js. I hope this helps.

**Comment by LinusBorg** [comment]
When i click on the link of the diff, github says there's nothing to show. 

Please check it.

**Comment by mbana** [comment]
@LinusBorg, thank you for the reply.

Both links work:

* https://github.com/banaio/vue_js_inline_fonts_bug/compare/working...master
* https://github.com/banaio/vue_js_inline_fonts_bug/blob/master/vue.config.js

> Vue-cli already has loader confif for fonts set up. You added additional config, so no both are applied to the fonts, which likely messes them up.

I don't understand what you here. What is _both_?

By the way, are you able reproduce the bug?

---

If this makes any sense to anyone: From further debugging it seems like the base64-encoded string that the browser is trying to load is a base64-encoded module that loads the fonts **not** the base64 encoded font itself. If you decode this base64-encoded string you will see what I am referring to. Also, the base64-encoded string of the font is way too be small to be the font so that's another hint that something else is going wrong.

**Comment by LinusBorg** [comment]
> If this makes any sense to anyone: From further debugging it seems like the base64-encoded string that the browser is trying to load is a base64-encoded module that loads the fonts not the base64 encoded font itself.

It makes sense to me - it's the result of what i was trying to explain in my previous reply.

You seem to be aware that vue CLI 3 already [has some loader preconfigured to handle font files](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js#L122-L127). you refer to it in the comment of your vue.config.js file:

> ```javascript
> /* config.module.rule('fonts').use('url-loader') */
> ```

Your mistake is that you seem to think that adding an alternative loader in the way that you do would replace this existing loader; It doesn't. 

If you run `vue-cli-service inspect`, you will find that you now have *both* the old url-loader and the new url-loader that you added in your config. 

Consequently webpack will apply *both* loaders for the font files (webpack doesn't stop after it finds one matching rule, it applies all matching rules & loaders).

Which is how you end up with a font file that is encoded twice - once by url-loader, once by file-loader.

----

Now, it seems all you want to to do is change the `limit` setting of the url-loader.
```javascript
chainWebpack: config => {
  config.module.rule('fonts').use('').use('url-loader').tap(options => {
    options.limit = 1
    retrun options
  })
}
```

This will adjust the existing config instead of adding a second one.

**Comment by mbana** [comment]
@LinusBorg, much appreciated. Thank you.
For anyone reading this is a not a issue. Sorry for the confusion.
