### ISSUE TITLE
vue.config.js 不能修改 html-webpack-plugin 配置 ( Can't be modified Configuration)

### ISSUE THREAD

**Issue by 672064406zerui** [vuejs/vue-cli#3297]
### Version
3.0.0

### Node and OS info
node 8.10.0

### Steps to reproduce
```
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
  configureWebpack: {
    plugins: [new HtmlWebpackPlugin({
        title: "demo",
        css: [
          "//cache.amap.com/lbs/static/main1119.css", "/public/common-loading.css"
        ],
        js: ["//cdn.polyfill.io/v2/polyfill.min.js"],

      })]
  }
 }
```

### What is expected?
Resources can be loaded with htmlWebpackPlugin.options cdn

### What is actually happening?
yarn serve err 
[Vue warn]: Cannot find element: #app

---
Is this configuration wrong? if not, how can I improve it?

**Comment by 672064406zerui** [comment]
### index.html
<% for (var i in htmlWebpackPlugin.options.js) { %>
        <script src="<%= htmlWebpackPlugin.options.js[i] %>"></script>
<% } %>

**Comment by LinusBorg** [comment]
You are adding a new, second plugin, but oyu really want to extend the existing plugin. Also, there are no `js` and `css` options.

Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
