### ISSUE TITLE
please include workbox over npm instead of downloading it over https

### ISSUE THREAD

**Issue by yennor** [vuejs/vue-cli#3361]
### What problem does this feature solve?
The service-worker.js generated by vue cli includes workbox over an https link:
"https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js".
One of the reasons I use npm is that I don't want the end application to download scripts from everywhere on the internet.
Additionally for me the above behaviour makes development more difficult, since it happens quite often that I'm developing without having an internet connection. So then above include obviously doesn't work.
So if workbox would be included as npm module, that would be great :-).

### What does the proposed API look like?
The api wouldn't change.
Just add workbox-sw dependency to pwa plugin.

**Comment by LinusBorg** [comment]
the workbox webpack plugin has an option for that, called [`importWorkboxFrom`](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_generatesw_config)

```javascript
module.exports = {
  pwa: {
    workboxOptions: {
      importWorkboxFrom: 'local',
    }
  }
}
```

**Comment by jbuhacoff** [comment]
Other javascript, css, font, and icon dependencies are downloaded using npm, and in production builds these other assets are compressed and copied into the dist directory. Most of them are also available on CDN but copying the assets to the local project is a good choice because it decouples the website/app from other people's CDNs, and the website/app owner can still put the output files on any CDN they choose. 

Making `importWorkboxFrom: 'local'` the default would match the way the rest of the application is built.

There's also a good point being made at [Issue #539 in vuepress](https://github.com/vuejs/vuepress/issues/539) about making the build output privacy-sensitive by default.
