### ISSUE TITLE
关于mac系统vue-cli下载的模板依赖不全的问题

### ISSUE THREAD

**Issue by fetjq** [vuejs/vue-cli#340]
您好，我的vue-cli版本号为2.8.1,系统为OSX10.12.3，在使用vue init webpack projectname执行模板安装时，会出现依赖安装不全的情况导致使用npm run dev编译失败，提示缺少的nodejs模块为strip-ansi,ansi-html,html-entities.这几个模块需要手动安装。
另外我在windows下使用同样的操作时，所有的模块都能正常安装。不过在windows下的代码迁移到mac上时，提示缺少的依赖更多，除了上面的依赖需要手动安装外，还有throttle-debounce/debounce,throttle-debounce/throttle这两个模块无法安装，我手动使用npm install时，会提示没有权限。
第二个系统迁移出现不兼容找不到可能是正常现象吧，关于第一个需要手动安装几个依赖的问题，劳烦您有空解决下。
如果是我本人操作的问题，请怒斥我，谢谢尤老师。

**Comment by posva** [comment]
Thank you for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there. Come back (to the relevant template repo) open a new issue if you find out there's a real issue

---

Translation may have translated things wrong, but if the npm installation failed then it's normal for the `npm run dev` command to fail

**Comment by yyx990803** [comment]
依赖装不下来跟 Vue 没有关系，这是 npm 的问题。建议你用国内的 npm 镜像源，稳定一点。

**Comment by yuzhougit** [comment]
我也碰到一样的问题，我用的就是国内的镜像源cnpm安装的

**Comment by kevinchung1026** [comment]
用国内的 npm 镜像源，意思是你把 npm 源设置为淘宝的，不用cnpm的命令
