### ISSUE TITLE
vue.config.js - configureWebpack: optimization problem

### ISSUE THREAD

**Issue by katonada** [vuejs/vue-cli#3454]
### Version
3.4.0

### Reproduction link
[https://github.com/katonada/vue.config/blob/master/vue.config.js](https://github.com/katonada/vue.config/blob/master/vue.config.js)

### Environment info
```
 System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @kazupon/vue-i18n-loader: ^0.3.0 => 0.3.0
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.0
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0
    @vue/cli-plugin-e2e-cypress: ^3.4.0 => 3.4.0
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0
    @vue/cli-plugin-unit-mocha: ^3.4.0 => 3.4.0
    @vue/cli-service: ^3.4.0 => 3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/component-compiler-utils:  2.5.2
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: ^1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue:  4.7.1
    vue: ^2.6.5 => 2.6.5
    vue-cli-plugin-django: ^0.1.3 => 0.1.3
    vue-cli-plugin-i18n: ^0.5.1 => 0.5.1
    vue-cookie: ^1.1.4 => 1.1.4
    vue-dayjs: ^1.0.2 => 1.0.2
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-i18n: ^8.8.1 => 8.8.1
    vue-intersect: ^1.1.2 => 1.1.2
    vue-line-clamp: ^1.3.2 => 1.3.2
    vue-loader:  15.6.2
    vue-meta: 1.5.8 => 1.5.8
    vue-mq: ^1.0.1 => 1.0.1
    vue-nprogress: ^0.1.5 => 0.1.5
    vue-router: ^3.0.2 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.5 => 2.6.5
    vue-template-es2015-compiler:  1.8.2
    vue-text-dot: ^1.0.0 => 1.0.0
    vue-timers: ^1.10.0 => 1.10.0
    vue-tiny-slider: ^0.1.31 => 0.1.31
    vue-video-player: ^5.0.2 => 5.0.2
    vuebar: 0.0.20 => 0.0.20
    vuex: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
When uncomment optimization: {  splitChunks: { ...}} part, build works, serve is working, no errors shown but the project in browser shows blank screen and console shows no error.

### What is expected?
The project works without the optimization part as it should. It's expected to work with optimization too.

### What is actually happening?
With optimization, there is blank screen in browser and no errors, network and all in dev tools

---
By applying any SplitChunksPlugin rules that blank screen is happening :( e.g. splitChunks: { chunks: 'all' }
Webpack optimization rules (https://webpack.js.org/configuration/optimization/).
SplitChunksPlugin https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by katonada** [comment]
OK, I got It, find the bug.
I misunderstood webpack code splitting so didn't include additional vendor files into html template.
I'm closing this issue.

**Comment by sharvilak11** [comment]
@katonada how did you solve this ? I am actually stuck in a similar situation where my view is blank and only thing I have applied is below. 

```
optimization: {
            runtimeChunk: 'single',
            splitChunks: {
                chunks: 'all',
                maxInitialRequests: Infinity,
                minSize: 120000,
                maxSize: 250000,
                cacheGroups: {
                    vendor: {
                        test: /[\\/]node_modules[\\/]/,
                        name(module) {
                            const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                            return `npm.${packageName.replace('@', '')}`;
                        },
                    },
                },
            }
        }
```

**Comment by katonada** [comment]
@sharvilak11 my case was VueApp on top of Django template that is used as SSR part. By splitting chunks I got new vendor file which I didn't include in Django template.

What can you see in the network part of dev tools? Is there missing some chunk or file 404?

**Comment by sharvilak11** [comment]
@katonada I am trying to split out the node_modules chunks since they will hardly be upgraded. It's a normal Vue project without any SSR. I don't see anything wrong in network, no such 404. I only get below warnings for preload and a blank view. I have also updated the previous comment with full configuration options which I have set in my vue.config.js

<img width="1672" alt="Screenshot 2020-04-23 at 11 40 03 AM" src="https://user-images.githubusercontent.com/19903825/80065155-4a18a700-8557-11ea-9cc6-d03ca38986f9.png">

**Comment by sodatea** [comment]
If it's a multipage app, please check if you have correctly added all the required chunk names in the `chunks` config in the page config entry. Like:

```
{
  pages: {
    'home': {
      // ...
      chunks: ['chunk-vendors', 'chunk-common', 'home', 'vendor']
    }
  }
}
```

**Comment by sharvilak11** [comment]
@sodatea Yes, it's a multi page app. Just one more doubt, I have lazily loaded some of the routes and have given chunk names via comments in my router config. Do I need to include those chunks as well in pages ?

**Comment by sodatea** [comment]
No, it's not required.

**Comment by sharvilak11** [comment]
@sodatea Thanks it worked with chunks in pages. Sorry to be a pain but just wanted to check if I pass minSize and maxSize for splitChunks it shows me the same blank screen I screenshotted above. If I don't specify the minSize and maxSize it works perfectly. Any idea why ?

```
const IS_VENDOR = /[\\/]node_modules[\\/]/;
config.optimization.splitChunks({
          //minSize: 1,
          //maxSize: 250000,
            cacheGroups: {
                vendors: {
                    name: 'chunk-vendors',
                    priority: -10,
                    chunks: 'initial',
                    minChunks: 2,
                    test: IS_VENDOR,
                    enforce: true,
                },
                ...['login', 'tenant'].map(key => ({
                    name: `chunk-${key}-vendors`,
                    priority: -11,
                    chunks: chunk => chunk.name === key,
                    test: IS_VENDOR,
                    enforce: true,
                })),
                common: {
                    name: 'chunk-common',
                    priority: -20,
                    chunks: 'initial',
                    minChunks: 2,
                    reuseExistingChunk: true,
                    enforce: true,
                },
            },
        });
```

```
pages: {
     login: {
            entry: './src/webapp/auth/login/login.js',
            template: 'public/index.html',
            filename: 'index.html',
            chunks: ['chunk-vendors','chunk-common', 'chunk-login-vendors', 'login']
        },
     tenant: {
            entry: './src/webapp/tenant/main.js',
            template: 'public/tenant/index.html',
            filename: 'tenant/index.html',
            chunks: ['chunk-vendors','chunk-common', 'chunk-tenant-vendors', 'tenant']
        },
}
```

**Comment by jacekkarczmarczyk** [comment]
> If it's a multipage app, please check if you have correctly added all the required chunk names in the chunks config in the page config entry

@sodatea I'm using the following code (taken from https://medium.com/hackernoon/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758#8c42) to split vendor chunks:
```js
optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      chunks: 'all',
      maxInitialRequests: Infinity,
      minSize: 0,
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name(module) {
            // get the name. E.g. node_modules/packageName/not/this/part.js
            // or node_modules/packageName
            const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

            // npm package names are URL-safe, but some servers don't like @ symbols
            return `npm.${packageName.replace('@', '')}`;
          },
        },
      },
    },
  },
```
and it generates chunks like this:
![image](https://user-images.githubusercontent.com/15625235/83740120-b6a6bb80-a656-11ea-9384-cef51f93f35a.png)

Do I need to add them to `chunks` manually? And every time I add some vendor dependency I need to remember to add it there as well?

**Comment by sharvilak11** [comment]
@jacekkarczmarczyk I was exactly trying to use what you used from the blog post and here are my findings. 

When you are dynamically creating chunks, it's difficult to supply chunks to your pages object in vue.config.js

As per my conversation with @sodatea , I dig deep into **html-webpack-plugin** repo and found it's possible to do with html-webpack-plugin@next version, possibly 4.x.x-alpha.xx . However this only works when you have a raw webpack configurations and not using it with vue-cli, because it requires a specific version of preload plugin whereas vue-cli has its own version of preload plugin due to which it fails during the build, so technically it's not achievable with current version of vue-cli's preload plugin.

Due to less bandwidth, I couldn't try checking further more on preload plugin and how can we make that work. But most probably it should work when the next version of vue-cli is out as it will by default support higher version of html-webpack-plugin by default. 

I will still leave for Haoqun to add further more if I have missed anything to add here.

**Comment by jacekkarczmarczyk** [comment]
Thanks for response, I've removed now the `optimizations` part, not very happy about this, I believe this issue should be opened though for further investigation

**Comment by jacekkarczmarczyk** [comment]
@sharvilak11 I think I've found a solution at least to my problem (still investigating but looks promising). So instead of defining `pages` in vue.config.js I'm running a separate build/serve script providing an entry file and destination folder:

```
    "serve:login": "vue-cli-service serve ./src/login.ts --open",
    "build:login": "vue-cli-service build ./src/login.ts --modern --silent --dest ./dist/login",
```

For multiple pages you would probably need some script that runs build script for each page instead of putting them into packages.json scripts

The other problem that you may find it's that all chunks (including vendor ones) are located in separate folders (`/dist` and `/dist/login` in my case), which means that they cannot be cached together, however some of them have the same filename (for example `vendor.axios.bfd77495.js` is located both in`/dist` and `/dist/login` folders) so I think it should be possible to find duplicates, removing them from `/dist/login` folder and telling the server to serve the cached version from /dist. I'm not working on this though as in my case it's not a priority

Hope it helps someone with the similar issue

**Comment by Mioleris** [comment]
Try by adding `chunks: all` to your page.index
```
  pages: {
    index: {
      entry: 'src/main.js',
      chunks: 'all'
    }
  }
```

**Comment by 33YANG** [comment]
@Mioleris I tried this won't work, single page will load all chunks, (in muti pages entry)

**Comment by heshimang** [comment]
> Try by adding `chunks: all` to your page.index
> 
> ```
>   pages: {
>     index: {
>       entry: 'src/main.js',
>       chunks: 'all'
>     }
>   }
> ```

this solved my problem

**Comment by Brass-neck** [comment]
> If it's a multipage app, please check if you have correctly added all the required chunk names in the `chunks` config in the page config entry. Like:
> 
> ```
> {
>   pages: {
>     'home': {
>       // ...
>       chunks: ['chunk-vendors', 'chunk-common', 'home', 'vendor']
>     }
>   }
> }
> ```

@sodatea Here has another problem. How do I know which chunks I need to write here ? I need to checkout all my code and find which chunks are imported in this entry, right ? Or there is any other better way to solve this problem ? Why not automatic ?
