### ISSUE TITLE
Vue-cli webpack and server backend dev hot-reaload

### ISSUE THREAD

**Issue by M-kasinski** [vuejs/vue-cli#351]
Hello,
 I am trying to understand how to specify the __hmr url.
Because when I include my file.js, for example http: // localhost: 8080 / app.js
In my page the hmr takes the address of my backend server http: // localhost: 2000 / __ hmr ... and refuses to load
Do you have a solution so that I can modify my configuration, in order to be able to reload my page automatically during my development
Thank you

**Comment by zigomir** [comment]
Hi @M-kasinski. I'm guessing you're using one of the [vuejs-templates](https://github.com/vuejs-templates), please open issue there.

Webpack's hmr should work out of the box.

I'm not really sure what's the issue but because you're mentioning different backend server I'll point you here: http://vuejs-templates.github.io/webpack/proxy.html
