### ISSUE TITLE
After the modification, the hot update needs to wait for more than 20 seconds.

### ISSUE THREAD

**Issue by qinkaiyuan** [vuejs/vue-cli#3594]
### Version
3.2.2

### Environment info
```
vue-cli3   typescript project 

Development mode

My project has more than 100 vue pages

Every time i modify a file, i need to wait 20 seconds for a hot update.

This is very influential in development efficiency.

Is there any good solution?

thanks.

--------------------------------------------------------------------------------------------------------------

vue-cli3   typescript项目，开发模式下，日常开发中

我们的项目拥有100多个vue的页面，

每次修改后热更新都需要20多秒，每改动一次都需要等待20多秒，这是非常痛苦的，非常影响我们的开发效率，请问有什么好的解决办法吗？

非常渴望您的答复，谢谢！

```

### Steps to reproduce
弄一个 一百多个vue页面的大型vue-cli typescript项目，每次修改后都需要等待重新编译，才能生效，这个过程一般都需要20多秒

### What is expected?
最好修改后立即生效，不需要等待热更新20多秒，

### What is actually happening?
每次修改后都需要等待20多秒

**Comment by sodatea** [comment]
Have you checked [this article](https://medium.com/@kenneth_chau/speeding-up-webpack-typescript-incremental-builds-by-7x-3912ba4c1d15) out?
According to the article there're several possible optimizations:
1. Enable `experimentalWatchApi` of `ts-loader` (since it's *experimental*, it comes with the risk of being buggy or unstable)
2. Turn off webpack `output.pathinfo`
3. Make sure you are using Node.js v8.11.2 or a higher version.

The final `vue.config.js`:
```js
module.exports = {
  chainWebpack: config => {
    config.output.pathinfo(false)
    config.module.rule('ts').use('ts-loader').tap(options => {
      options.experimentalWatchApi = true
      return options
    })

    // possibly speed up the rebuild further by disabling type checking, not recommended
    // config.plugins.delete('fork-ts-checker')
  }
}
```

---

Next time please consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
