### ISSUE TITLE
.env variables are being expanded when I don't want them to be

### ISSUE THREAD

**Issue by daviesdoclc** [vuejs/vue-cli#3596]
### Version
3.5.0

### Environment info
```
Sorry... I don't run vue globally.  It's just part of my project.  So not sure how to get this.
```

### Steps to reproduce
I have some urls inside my .env file like this

VUE_APP_GEOCODE_URL=https://maps.googleapis.com/maps/api/geocode/json?address=${address}&components=country:${country}&key=${key}

I use to be able to access this in my javascript as

process.env.VUE_APP_GEOCODE_URL and do parameter substitution with es6-dynamic-template (https://www.npmjs.com/package/es6-dynamic-template)

However, the latest version of vue-cli seems to have changed this, and is expanding the url for me (with non-existent variables).  I noticed this commit https://github.com/vuejs/vue-cli/pull/3534 that is using https://github.com/motdotla/dotenv-expand.  I suspect this is causing my issues.  How do we prevent it from processing our variables or how can I escape it so I control the substitution?

### What is expected?
Previous versions did not expand the environment variables.

### What is actually happening?
My environment variables are being expanded.  I use to do the substitution myself at runtime.

**Comment by daviesdoclc** [comment]
Ok... I should have tried this first...

VUE_APP_GEOCODE_URL=https://maps.googleapis.com/maps/api/geocode/json?address=\${address}&components=country:\${country}&key=\${key}

Seems to work.  Hopefully this helps someone else.

**Comment by sodatea** [comment]
Thanks for your feedback and glad to see that you found a workaround.

But we are unlikely to revert this feature.
Technically, every bug fix/ new feature can be a breaking change for someone relying on the buggy implementation. In this case, we see the auto-expand behavior as the more intuitive one, since every *nix system and most other similar utilities (e.g. create-react-app) expand environment variables by default.
