### ISSUE TITLE
Error when require/import

### ISSUE THREAD

**Issue by orblazer** [vuejs/vue-cli#3843]
### Version
3.6.3

### Reproduction link
[https://github.com/orblazer/gestion-tmp2](https://github.com/orblazer/gestion-tmp2)

### Environment info
```
System:
    OS: Linux 5.0 Antergos Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 11.14.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.3
  npmPackages:
    typescript: ^3.4.3 => 3.4.3 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Clone the repository
2. Start project with `yarn serve`
3. Check the console when open

### What is expected?
Import the file `@/locales/en.json` correcly

### What is actually happening?
This is make an error when import with that code : https://github.com/orblazer/gestion-tmp2/blob/master/src/plugins/i18n.ts#L66

---
I am sorry if that is not right place.

That is strange because i have try use `require('@/locales/en.json')` and that is work.
Edit: This is only on browser because i have try use wrong path and this make error on build.

**Comment by LinusBorg** [comment]
Hello @orblazer 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.

**Comment by sodatea** [comment]
See: https://webpack.js.org/api/module-methods/

> Fully dynamic statements, such as `import(foo)`, **will fail** because webpack requires at least some file location information. This is because `foo` could potentially be any path to any file in your system or project. The `import()` must contain at least some information about where the module is located, so bundling can be limited to a specific directory or set of files.

**Comment by orblazer** [comment]
Ok thanks @sodatea and sorry for the inconvenience.
