### ISSUE TITLE
How to remove `require("vue")` in library build mode?

### ISSUE THREAD

**Issue by NightCatSama** [vuejs/vue-cli#3951]
### What problem does this feature solve?

In some scenarios, unexpected errors will occur. (e.g. use components in `laravel`)

Currently encountering two kinds of errors.

The first one is `Super expression must either be null or a function`,  and i manually fix it after `require("vue")` is modified to `require("vue").default`.

The second is `[Vue warn]: $attrs is readonly.` and `[Vue warn]: $listeners is readonly.`, i haven't found the real reason for this problem, but I guess it is caused by vue reuse.

### What does the proposed API look like?
Can add a parameter to control whether `vue` is introduced because my component does not use `vue`.

**Comment by LinusBorg** [comment]
This issue doesn't provide enough information not a runnable reproduction. 

It's also likely related to how you use Vue in a specific scenario / with another library or tool, and not related to vue-cli. 

One thing I can say is that you see at let's the second error likely because you have two copies of Vue in your app. 

I can't say why, obviously. 

Please use forum.vuejs.org to ask for help for your app, or provide a real big report including a run able reproduction
