### ISSUE TITLE
Parse error on line 125

### ISSUE THREAD

**Issue by OmgImAlexis** [vuejs/vue-cli#401]
After running `vue init ~/code/simon twistly-frontend` I get this error. 
Template repo: https://github.com/OmgImAlexis/simon
```
? Project name twistly-frontend
? Project description Frontend for Twistly
? Author Alexis Tyler <xo@wvvw.me>
? Need a client? Yes
? Need a server? No
   vue-cli · Parse error on line 125:
...== 1) {      // x{{a,b}}y ==> x{a}y x{b
----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

**Comment by posva** [comment]
Handlebars is trying to parse that but it fails because it's not a syntax it knows. You should be able to escape it with `\{{}}`.

**Comment by OmgImAlexis** [comment]
@posva would it be possible to have something more descriptive added here as this doesn't really point back to the file with the issue instead of states there is one. Going through my code I can't actually find anything with that line in it as I'm assuming that's compiled code it's dealing with?

**Comment by calvernaz** [comment]
@posva @OmgImAlexis The patch definitely gives a better error description for what's going on, but soon you will realize the issue is handlebars trying to interpolate a file you don't care about like a file inside node_modules, in order to avoid these interpolation errors use the property **skipInterpolation**.

`"skipInterpolation": ["src/**/*.vue", "node_modules/**"]`
