### ISSUE TITLE
npm run serve启动项目后，浏览器会打开两个 http://localhost:8080 窗口

### ISSUE THREAD

**Issue by PursuitLife** [vuejs/vue-cli#4129]
### Version
3.8.2

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Environment info
```
windows 64位操作系统
```

### Steps to reproduce
1、vue create project 创建项目
2、配置项目启动端口：devServer:{
        port:"8080",
        open:true,
    }
3、npm run serve 启动项目

### What is expected?
npm run serve 启动项目时只打开一个 http://localhost:8080 窗口

### What is actually happening?
npm run serve 启动项目时打开两个 http://localhost:8080 窗口

**Comment by jiangxiaoxin** [comment]
**node_modules** 里有 **webpack-dev-server**，又用了 **vue-cli 3.0**，然后 **webpack-dev-server**里有个`runOpen`方法会打开一个窗口，**vue-cli**里的**cli-service**里在判断`isFirstCompile`之后又会调用**cli-shared-utils**里的`openBrowser`打开一个窗口，就导致开了两个窗口。怎么解决？不知道，我把自动开启关掉了。

PS: mac 上不会打开两个，代码里写了”尽量用打开过的窗口“

>// If we're on OS X, the user hasn't specifically
  // requested a different browser, we can try opening
  // Chrome with AppleScript. This lets us reuse an
  // existing tab when possible instead of creating a new one.

**Comment by RamirezET** [comment]
妈耶 果然是bug 今天遇到了我排查了半天 确认自己的配置没问题 老版本CLI生产的项目也问题 3.8.2生成的在在多个Windows 10下都打开两个···

**Comment by kuretru** [comment]
@jiangxiaoxin mac也有此bug，可见issue #4088

**Comment by sodatea** [comment]
Fixed in 3.8.3
