### ISSUE TITLE
babel-preset-latest deprecation warning at npm install

### ISSUE THREAD

**Issue by jkole** [vuejs/vue-cli#420]
Doing npm install -g vue-cli gives:

npm WARN deprecated babel-preset-latest@6.24.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template repo (I think you're using the [webpack one](https://github.com/vuejs-templates/webpack)) and provide some steps to reproduce the problem.
Thanks!

**Comment by jkole** [comment]
I'm not sure I understand. As noted in the issue, this warning is immediately after the very first npm install of the vue-cli package, not when creating a new skeleton with any particular template. In other words, the first experience a new user has when installing vue-cli for the first time is a deprecation warning...nothing to do with any specific template.

**Comment by posva** [comment]
Ups, closed a bit too fast. That warning appear because of a dependency in
vue-cli but the problem should be fixed somewhere else. I'll check it once
I'm home. It's probably a Vue preset

**Comment by mcaskill** [comment]
The deprecations comes from `vue-cli` requiring an old version of `babel-preset-vue-app:^0.4.0`.

The requirement for `babel-preset-latest` in `babel-preset-vue-app` was fixed in March 2017 ([0.5.0](https://github.com/vuejs/babel-preset-vue-app/releases/tag/v0.5.0)).

The `babel-preset-vue-app` package is currently at [1.2.1](https://github.com/vuejs/babel-preset-vue-app/releases/tag/v1.2.1) as of August 2017.

**Comment by tizmagik** [comment]
Just got this today -- is there any blockers to updating `babel-preset-vue-app`?
