### ISSUE TITLE
"vue serve | build" looks in scr/ for valid entry files aswell

### ISSUE THREAD

**Issue by bmacher** [vuejs/vue-cli#4207]
### What problem does this feature solve?
When I open a vue project in my ide the terminal points on the root directory of the project. When I type in "vue serve" it tells that no valid entry point is found an I should rather use "npm run serve". A little change in the "cli-service-global" package could solve the problem.

### What does the proposed API look like?
No change on the api.

**Comment by bmacher** [comment]
I already made the necessary change which passed all tests, but I am not allowed to push any commits even in a new branch. Could any one tell me how I have to handle the change?

- I am kind of new in open source. :-)

**Comment by sodatea** [comment]
Could you elaborate on the use case?
I think if there's a `src/` folder and a `package.json`, the user is expected to have an actual project to run. Typing `vue serve` is more likely a misunderstanding of the command usage.

**Comment by bmacher** [comment]
Well I would love to use `vue serve` the same way as `ng serve` in angular. With `ng serve` you can start the application from the `project` and `project/src` directory but with `vue serve`you always have to be in `project/src`. Maybe I miss understand `vue serve`.  Yes, I could use `npm run serve` but I find `vue serve` more handy.

**Comment by sodatea** [comment]
Well, then you did misunderstand `vue serve`.

Unlike Angular CLI, Vue CLI tries to empower the built-in functionalities of `npm` and other common toolings. We try to provide a good default setup while still enabling users to do more customization on their wish.
Essentially, it is a scaffolding tool with some nice features, not a one-stop solution for all your Vue projects. This is because with limited resources we as the maintainers cannot cover every single use case of the community, we have to make customization easy.

To achieve that goal, locality is one of our essential design principles. The global CLI is decoupled from the bundler and plugins setup. Users should be able to run the project even without any knowledge of the CLI utility - it's just yet another node project anyway.
So the actual command to serve the project is `vue-cli-service serve`, wrapped by `npm run serve`. The `vue serve` is only for quick prototyping as we made it clear in the documentation https://cli.vuejs.org/guide/prototyping.html
And we did notice that some users who use Vue CLI without knowing Node or npm very well may be confused, so we intentionally run an additional check on `package.json` https://github.com/vuejs/vue-cli/pull/3508
