### ISSUE TITLE
Can I move the 'vue.config.js' to other folder?

### ISSUE THREAD

**Issue by pikadun** [vuejs/vue-cli#4216]
### What problem does this feature solve?
I want to keep my root directory clean 

### What does the proposed API look like?
I can specify the path to `vue.config.js` in `package.json` or `cli-service` automatically scans the directory where `vue.config.js` is the root directory.

**Comment by sodatea** [comment]
> There will not be a first-class option for this because we prefer all Vue CLI projects to have a consistent, standard directory structure. Using a different directory name is only a matter of personal taste, so if you insist on changing that, you are on your own.

https://github.com/vuejs/vue-cli/issues/1134#issuecomment-384856754

This is an unnecessary maintenance burden for us so we are not likely to support it.

**Comment by pikadun** [comment]
[this can slove my problem](https://stackoverflow.com/questions/52131843/specify-a-vue-cli-vue-config-js-location)

**Comment by sodatea** [comment]
Note: this is an undocumented flag; we have no plan to remove it in the foreseeable future but there's also no guarantee of full official support for it. For now, this workaround may work fine for your project, but due to lack of testing, other new features may or may not work well with this flag, you are on your own in that case.

**Comment by basickarl** [comment]
It's ridiculous the Vue forces this. Here is how we fixed it in the package.json scripts:
 
` "development": "npm exec -- nodenv --env configs/.env.development --exec npm -- exec -- vue-cli-service serve",`
