### ISSUE TITLE
Error: No files matching 'src' were found.

### ISSUE THREAD

**Issue by wuyuweixin** [vuejs/vue-cli#4278]
### Version
3.9.2

### Reproduction link
[https://github.com/wuyuweixin/vue-cli-eslint-demo](https://github.com/wuyuweixin/vue-cli-eslint-demo)

### Environment info
```

Environment Info:

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. git clone https://github.com/wuyuweixin/vue-cli-eslint-demo.git
2.yarn install
3.yarn run lint

### What is expected?
Not Error throw.

### What is actually happening?
Throw Error: No files matching 'src' were found.

**Comment by sodatea** [comment]
That's why we discourage users to change their default directory structure. (more discussions at https://github.com/vuejs/vue-cli/issues/3040 and https://github.com/vuejs/vue-cli/issues/3061)
It would be a tremendous burden for us to deal with all the possible customizations.
As in this case, it is because the eslint plugin assumes a default list of files to lint, and none of them exists in the project:
https://github.com/vuejs/vue-cli/blob/ddfdd1af2492b2f7bbcbb537d0f35c1ef67d53a0/packages/%40vue/cli-plugin-eslint/lint.js#L55-L70

A simple fix is to just add a second argument for the lint command:
```
yarn lint web
```

**Comment by wuyuweixin** [comment]
![image](https://user-images.githubusercontent.com/16173597/61118052-826c5e80-a4ca-11e9-807d-bcec41394b58.png)

**Comment by wuyuweixin** [comment]
Thanks @sodatea

**Comment by wuyuweixin** [comment]
In fact,src directory exists.

**Comment by wuyuweixin** [comment]
I deleted the src directory,and rerun yarn lint not error throw

**Comment by sodatea** [comment]
Since ESLint 5, by using its node API, it will throw if the provided glob pattern does not match any file to lint. There's a `src` directory but it does not contain any js files, so the program throws.

**Comment by wuyuweixin** [comment]
😂

**Comment by wuyuweixin** [comment]
Bug of eslint.

**Comment by sodatea** [comment]
And you should not run `yarn lint` without arguments if your js files are not under any of the default directories. You have to specify the path to lint.

**Comment by sodatea** [comment]
It's not a bug, **it's a feature**. You are using the tools the wrong way.

**Comment by wuyuweixin** [comment]
https://github.com/eslint/eslint/issues/10587

**Comment by sodatea** [comment]
1. The linked issue is not marked as a "bug" but an "enhancement"
2. In your case, it works perfectly as intended. **It is expected to throw if there's no js file in `src/`**. It works as a reminder: now that you don't follow the default directory structure of Vue CLI, you are expected to provide a path argument to the lint command rather than just use the default. By calling "yarn lint" without arguments, `web/` is not checked at all, I'm sure that is not what you intended to do.

**Comment by wuyuweixin** [comment]
Thank you very much.
