### ISSUE TITLE
use @vue/babel-preset-app without vue-cli3,  polyfills is not working

### ISSUE THREAD

**Issue by taoche** [vuejs/vue-cli#4316]
### Version
3.9.3

### Environment info
```
node: 10.16.0
yarn: 1.17.3
"@babel/core": "7.5.5",
"@vue/babel-preset-app": "3.9.2",
```

### Steps to reproduce
in vue-cli code

https://github.com/vuejs/vue-cli/blob/v3/packages/%40vue/babel-preset-app/index.js#L128

`exclude: polyfills.concat(exclude || []) `

It excludes the `defaultPolyfills` when `userPolyfills` is undefined.

I improvised the problem:

```
presets: [
    [
      '@vue/app',
      {
        polyfills: [],
      },
    ],
  ],
```

### What is expected?
fix this bug

### What is actually happening?
polyfills setting is not working

**Comment by sodatea** [comment]
I think you might have misunderstood the use case.
Those polyfills are excluded because they have already been handled by the polyfills plugin https://github.com/vuejs/vue-cli/blob/c36eabcf891ebe214a877213ae51372b4dd6f1d4/packages/%40vue/babel-preset-app/index.js#L110-L113

If you are using this preset outside Vue CLI projects, please provide an `entryFiles` option https://github.com/vuejs/vue-cli/tree/v3/packages/%40vue/babel-preset-app#entryfiles
