### ISSUE TITLE
Vue delimiters does not work with golang  

### ISSUE THREAD

**Issue by AttSee** [vuejs/vue-cli#434]
hi great job
but 
Golang uses {{}}
vuejs uses {{}}
I change delimiters
new Vue({
  delimiters: ['${', '}']
})

but not working with golang

**Comment by LinusBorg** [comment]
Hello @AttSee 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by posva** [comment]
The docs has a great search. We encourage you to use them: https://vuejs.org/v2/api/#delimiters
