### ISSUE TITLE
Webpack Dev Server should update to a new version

### ISSUE THREAD

**Issue by lwxbr** [vuejs/vue-cli#4373]
### Version
3.9.2

### Reproduction link
[https://github.com/webpack/webpack-dev-server/issues/2158](https://github.com/webpack/webpack-dev-server/issues/2158)

### Environment info
```
Webpack Dev Server: 3.1.4
Webpack: 4.15.1
```

### Steps to reproduce
Read the link and you will understand the problem.

### What is expected?
The Webpack Dev Server should run without problem.

### What is actually happening?
There is a problem in validation of liveReload option.

---
Please, read that thread and you will understand why the update is needed: https://github.com/webpack/webpack-dev-server/issues/2158

See also: https://github.com/vuejs/vue-cli/issues/4368

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/blob/c36eabcf891ebe214a877213ae51372b4dd6f1d4/packages/%40vue/cli-service/package.json#L80

I think it's due to your local npm cache.
Please remove `package-lock.json`, run `npm cache clean -f` and then rerun `npm install` in the project directory.

Also, next time, please provide a reproduction.
