### ISSUE TITLE
Make vue --version print both the CLI version and the current version of Vue in use in the current directory

### ISSUE THREAD

**Issue by lloydjatkinson** [vuejs/vue-cli#4514]
### What problem does this feature solve?
Currently `vue --version` will show the version of the CLI. It does not show the version of Vue being used in the current directory.

This is potentially confusing if someone ran `vue --version` which told them 3.11.0 causing them to think they are using Vue 3.

### What does the proposed API look like?
NA

**Comment by LinusBorg** [comment]
That would make it harder for other tools to run `vue --version` to get the current vue-cli version

**Comment by lloydjatkinson** [comment]
Perhaps a new flag could solve that problem?

**Comment by sodatea** [comment]
I don't think output the vue version used in the current directory is a good idea because there's already a `vue info` command for this usage. This also adds too much complexity to the should-be-simple `--version` command.

But to avoid confusion, I propose to add a `Vue CLI ` prefix to the version field. See https://github.com/vuejs/vue-cli/pull/4681

**Comment by lloydjatkinson** [comment]
This is great, thank you 👍
