### ISSUE TITLE
Webpack and HTTP2

### ISSUE THREAD

**Issue by pablohpsilva** [vuejs/vue-cli#458]
Hello! How do you do?

I would like to have an option on webpack template to support HTTP2. The thing is: The build of my project + vendors are up to 3Mb size! I looked for any way to create chunks of the bundle so I could use HTTP2 requests and load the application faster.

Does anyone knows if this can be done?

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) also, this is not related to Vue and it's not the right repository

**Comment by mhluska** [comment]
@posva I think he's asking how to get http 2 when using `vue-cli-service serve` since it does http 1.1 by default. I'm curious about this as well.

**Comment by bediu** [comment]
Anyone solved this issue? I need those lighthouse fireworks so bad

**Comment by hhsmax** [comment]
@bediu *vue-cli-service serve* is using *webpack-dev-serve* to host the project & according to their [documentation](https://webpack.js.org/configuration/dev-server/#devserverhttp2) http2 is not supported at the moment because spdy (library for serving http2) is broken & not used for node.js > v10.0. They planned to migrate over to node.js built-in http2 support but with this [thread](https://github.com/expressjs/express/issues/3388) seems like it will take a while.
