### ISSUE TITLE
make the WebDriver dependencies optional for the Nightwatch.js plugin

### ISSUE THREAD

**Issue by hohlb** [vuejs/vue-cli#4617]
### What problem does this feature solve?
Right now, ChromeDriver gets installed for Chrome and GeckoDriver for Firefox. But our end-to-end tests run inside our continuous delivery docker image which has them already installed outside of npm, so this is not necessary. It actually adds more complexity, because all our developers have to be aware that the ChromeDriver and GeckoDriver npm dependencies are not needed. Unfortunately, they now have to stay inside the devDependencies in package.json, otherwise error messages appear because they are required as npm packages.

##### When running
Especially when using the `--config` flag to use a custom nightwatch config file, you should not `require()` them when running `npm run test:e2e`:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/index.js#L24

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/index.js#L32

Maybe you could make this dependent on the `--config` flag? We can then set the path to the WebDrivers in our custom nightwatch.js config to point to the "globally installed" WebDrivers.

##### During installation
What also would be helpful is an option to not add the `chromedriver` and `geckodriver` npm packages to `devDependencies` in the first place.

**Comment by sodatea** [comment]
The code does need to be fixed - but I think there're better ways to avoid such problems in your project setup.

As far as I know, there're various ways to skip WebDriver download for the 2 packages:
1. [`CHROMEDRIVER_SKIP_DOWNLOAD`](https://github.com/giggio/node-chromedriver#skipping-chromedriver-download) & [`GECKODRIVER_SKIP_DOWNLOAD`](https://github.com/vladikoff/node-geckodriver#skipping-geckodriver-download) environment variables;
2. [`CHROMEDRIVER_FILEPATH`](https://github.com/giggio/node-chromedriver#custom-binaries-file) & [`GECKODRIVER_FILEPATH`](https://github.com/vladikoff/node-geckodriver#using-a-cached-download) pointing to the local archive paths.

I think it is better to keep the dependencies in the project (because they *are* dev dependencies by definition) and use the above tricks to avoid the extra downloading costs.
This also makes the project setup more environment-agnostic, which could reduce the future maintenance burden.
