### ISSUE TITLE
How to integrate the cli with Wordpress

### ISSUE THREAD

**Issue by saqlain5544** [vuejs/vue-cli#4865]
### What problem does this feature solve?
Integrating the Vue js with WordPress solves the problem of creating SPAs. I want to build SPA with WordPress using Vue cli but I don't know how to do it, or even if I can do so.

### What does the proposed API look like?
I don't know.

**Comment by LinusBorg** [comment]
Hello @saqlain5544 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
