### ISSUE TITLE
test:unit support mode env

### ISSUE THREAD

**Issue by Phinome** [vuejs/vue-cli#5007]
### What problem does this feature solve?
just like build mode, support test:unit --mode xxx.

when using multiple mode to build, it expect testing at current mode.

for example:

build:
external build: vue-cli-service build --mode=external

test:
external test: vue-cli-service --mode=external test:unit

Thanks

### What does the proposed API look like?
vue-cli-service --mode xxx test:unit [options] [files]

**Comment by LinusBorg** [comment]
Can you please describe a real use case for this?

Env variables are usually used for stuff like different API endpoint urls, API keys and similar things. Since you don't want to actually hit any API endpoints in unit tests, these values are useless during test and should rather be replaced with dummy values.

In other words: I can't imagine a scenario where I would really want to run my unit tests with env variables of my `staging` mode, for example - so I would ask you to provide me with one.

Technically, unit tests are coupled to having `NODE_ENV=test`, so what you are asking would require a breaking change of the current implementation of modes and env variables. So without a good usecase, we won't consider that.

**Comment by Phinome** [comment]
i agree with you.

**Comment by Phinome** [comment]
i agree with you.
in our case, we use mode to build multiple mode with same code, just like: 'external' and 'internal'. it needs test, before the application to build online. But, we do not take jest as unit test. it is treated integration test with vuex modules and services and others without ui cases, so supportting modes to make the test work at each mode. 
You know what I am talking about?
