### ISSUE TITLE
Change /dist to /public in .gitignore

### ISSUE THREAD

**Issue by fedtti** [vuejs/vue-cli#5131]
### Version
4.1.2

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 13.7.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.13.7 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-router: ^4.1.0 => 4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.0 => 4.1.2
    @vue/cli-shared-utils:  4.1.2
    @vue/component-compiler-utils:  3.1.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.10 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router: ^3.1.3 => 3.1.5
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
`vue create _foo_`

### What is expected?
Adding `/public` to `.gitignore`

### What is actually happening?
`/dist` is added to `.gitignore`

---
I saw that `.gitignore` by default adds `/dist` to the ignored folders, but Vue CLI uses `/public` instead. It makes sense to change the folder name in `.gitignore`, IMHO.

**Comment by LinusBorg** [comment]
No, I think you misunderstand what the directories are for?

`/public` contains static assets that should end up in the final build. This directory should definitely be submitted to git.

`/dist` contains the final build of the app (or library). It doesn't have to be added to git as it can be build from the sources whenever needed. That's why it's in gitignore.

Some people like to add the content of /dist to git as well. They can just remove the ignore entry in that case
