### ISSUE TITLE
Every vue cli command hangs

### ISSUE THREAD

**Issue by peschee** [vuejs/vue-cli#5310]
### Version

4.2.3

### Environment info

```
node: 10.16.3
npm: 6.9.0
osx: 10.15.3
shell: zsh
```

### Steps to reproduce

- `npm install -g @vue/cli`
- run `vue info` or `vue --version`

### What is expected?

- `vue info` outputs the environment information
- `vue --version` outputs the vue cli version

### What is actually happening?

Both commands hang and do not output anything.

---

I also tried this with `npm install -g @vue/cli@3.12.1` but the problem remains almost the same. `vue --version` outputs the version, `vue info`  only outputs

```
Environment Info:
```

but nothing more and hangs.

Anybody with any ideas why this might be happening?

**Comment by sodatea** [comment]
Don't use `vue-cli`. It does not support the `vue info` command, thus outputting nothing.

As for `@vue/cli`, I'm not sure what the problem. But could you try to run `npx envinfo`? The `vue info` command depends on that package to collect the environment information. So if it works, there's a problem in `@vue/cli`; otherwise, the bug is in the `envinfo` package.

**Comment by peschee** [comment]
@sodatea I have adapted the description. I'm not using `vue-cli`, but `@vue/cli`, sorry for that confusion. The problem is not with the `info` command of vue cli, but the cli in general. I cannot run any command for that matter. I noticed this when using the `vue-cli-service` in our project.

That command stopped working so right now, I cannot build, serve, test etc. the project. I narrowed it down to the fact that all `vue ...` commands also hang on my machine. Cannot figure out why unfortunately.

**Comment by sodatea** [comment]
Well that must be the culprit.
I don't know why `mdfind` hangs on your machine but there is a bug in the current `@vue/cli` implementation that it tried to get the browser version when not necessary. A similar bug was reported recently too https://github.com/vuejs/vue-cli/issues/5286#issuecomment-602527197

Maybe it's because the Spotlight index hasn't been successfully built in your system?

Anyway, the workaround is to modify the installed `@vue/cli` source code to stop this getter from running.
https://github.com/vuejs/vue-cli/blob/f1bdf7319ac3daa54d57589fc99d7b33696ac0a1/packages/%40vue/cli-shared-utils/lib/env.js#L183-L185 (`if (hasCheckedBrowsers)` -> `if (true)`)

**Comment by peschee** [comment]
I was able to narrow down my issue. The problem was that the `mdfind` command, which vue cli (or `vue-cli-service` for that matter) seems to use was running too long on my machine (more or less endlessly…).

I used the following command `$ mdfind -name stdlib.h` for testing. The issue for me was that I had referenced to mounted drives `~/Library/Containers` and Spotlight seemed to be indexing these directories. Therefore, the `mdfind` command was blocking the execution of all vue cli / cli service commands.

I explicitely excluded `~/Library/Containers` from the Spotlight index. The vue commands work now as expected.
