### ISSUE TITLE
no babel compiler class expression

### ISSUE THREAD

**Issue by 150148313** [vuejs/vue-cli#5425]
### Version
4.3.1

### Reproduction link
[https://github.com/150148313/vue-cli-demo.git](https://github.com/150148313/vue-cli-demo.git)

### Environment info
```
windows 10

```

### Steps to reproduce
yarn build
watch /dist/static/js/chunk-vendors.js  
have class expression

### What is expected?
 compiler class expression

### What is actually happening?
 no compiler class expression

**Comment by LinusBorg** [comment]
Your tsconfig is targeting `esnext`, but your babel config still transpiles to es5 because of the `browserslist` settings in package.json here:

https://github.com/150148313/vue-cli-demo/blob/master/package.json#L55-L60

Adjust that to cover evergreen browsers only, and your bundle will contain class expressions etc.

**Comment by 150148313** [comment]
> i
I do not want contain class expressions etc，class expression incompatible in IE

**Comment by 150148313** [comment]
@LinusBorg

**Comment by LinusBorg** [comment]
But in your original issue post you sa you *do* want class expressions. I don't understand what you want

**Comment by 150148313** [comment]
@LinusBorg I was wrong，I find class expression in chunk-vendors.js,but I don't need it, it  incompatible some browser.

**Comment by sodatea** [comment]
Can't reproduce. No `/dist/static/js/` folder. I don't think it's the actual reproduction project.

**Comment by 150148313** [comment]
@sodatea I'm sorry, it's OK now
