### ISSUE TITLE
Fedora32 support

### ISSUE THREAD

**Issue by gawaxx** [vuejs/vue-cli#5518]
### What problem does this feature solve?
I'm using fedora32 yet I can't install vue cli-service because it doesn't support fedora32. I would also like the ability for the users to use the beta version, which can sometimes be a fix when trying to troubleshoot an app. 

Error that I get:

npm http request GET https://registry.npmjs.org/@vue%2fcli-service
npm ERR! Linux 5.6.12-300.fc32.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@vue/cli-service"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

### What does the proposed API look like?
Just have a repo for Fedora32

**Comment by sodatea** [comment]
The problem is not on the Vue CLI side, neither the OS version:

1. The node / npm version is too old. Vue CLI only supports Node.js v8.9+ (and v10.12+ is recommended because v8.x has reached end-of-life).
2. `EAI_AGAIN` is a network error that most likely caused by the DNS server. Please check your network setup.
