### ISSUE TITLE
Error occurred while trying to proxy request to an https host

### ISSUE THREAD

**Issue by KangKai-fe** [vuejs/vue-cli#553]
When I tried to proxy request to an https host, I got 'EPROTO' error, help, please.

``` javascript
// config/index.js
proxyTable: {
  '/salt': {
    target: 'https://192.168.1.234:8443',
    changeOrigin: true
  }
}
```

my host: ``` http://192.168.1.233:8080 ```
api server host: ``` https://192.168.1.234:8443 ```

error log: 

```
[HPM] Error occurred while trying to proxy request /salt/salt2rice/bask/lisNewtByPublish?pageSize=5&pageIndex=1 from 192.168.1.233:8080
to https://192.168.1.234:8443 (EPROTO) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
This looks related to a specific template as well, so make sure to provide the name of the template you're using, if it turns out to actually be a bug, please, report it to the template's repository
