### ISSUE TITLE
Is 'eval-cheap-source-map' a valid webpack.devtool value?

### ISSUE THREAD

**Issue by svewag** [vuejs/vue-cli#5729]
### Version
4.5.0

### Environment info
```
-
```

### Steps to reproduce
According to https://github.com/vuejs/vue-cli/blob/master/packages/@vue/cli-service/lib/commands/serve.js the devtool option for webpack in non-production mode is 'eval-cheap-source-map'.

But I do not find any information about this type of value in the webpack docs or code

- https://github.com/webpack/webpack/blob/master/examples/source-map/webpack.config.js
- https://webpack.js.org/configuration/devtool/

### What is expected?
A valid devtool option

### What is actually happening?
An invalid devtool option is used.

**Comment by sodatea** [comment]
Thanks for the finding! The value we used can't be found in the documentation because the enforced pattern wasn't introduced until earlier this year https://github.com/webpack/webpack.js.org/pull/3507

And the old pattern still works because in the source code webpack uses `.includes` to look for the matching parts https://github.com/webpack/webpack/blob/90472d97bacd67ad027a4b4acd182b3e581b5382/lib/WebpackOptionsApply.js#L232-L261 Currently I don't see any validation on the order.

**Comment by svewag** [comment]
Thank you 🙏
