### ISSUE TITLE
General Loading is slow

### ISSUE THREAD

**Issue by LokotamaTheMastermind** [vuejs/vue-cli#5751]
### What problem does this feature solve?
> Please fix the issue of slow startup loading time on windows and also the option of select destination folder, it is too slow when loading! Thanks

### What does the proposed API look like?
I don't know much about API's

**Comment by sodatea** [comment]
> slow startup loading time on windows

How slow? How big is the project?

> the option of select destination folder

It's already supported with the `outputDir` option https://cli.vuejs.org/config/#outputdir

**Comment by LokotamaTheMastermind** [comment]
## First the startup time of the vuecli is slow and not fast.

## Second the project was the basic skeleton of a vue application.

**Thanks for asking**

**Comment by sodatea** [comment]
I mean, how slow? Tens of seconds? Minutes?

If it takes more than one minute, there must be a bug.
Otherwise, if it takes twenty or thirty seconds for the initial build and then a few seconds for recompilation, I think it's still acceptable. After all, Vue CLI provides so many built-in functionalities.

For faster compilation, you can try out [Vite](https://github.com/vitejs/vite)

**Comment by LokotamaTheMastermind** [comment]
#### _**Tried it again it's now faster.**_

> **But there is still an issue but I'm gonna open another issue and close this one**
