### ISSUE TITLE
HMR not work on macOS

### ISSUE THREAD

**Issue by geekduck** [vuejs/vue-cli#5803]
### Version
4.5.4

### Environment info
```
OS: macOS Catalina 10.15.6
Browser: Chrome 84.0.4147.135
Nodejs: 12.18.3
NPM: 6.14.8
```

### Steps to reproduce
1. $ npm i -g @vue/cli

2. $ vue create sample-project

3. $ cd sample-project && npm run serve

4. Edit sample-project/src/App.vue

### What is expected?
Browser reload automatically

### What is actually happening?
Browser doesn't reload

---
Windows10 + Chrome84 ... HMR works

Ubuntu20.04 + Chrome84 ... HMR works

**Comment by sodatea** [comment]
Has the project recompiled?
Are there any error logs on the Chrome console?

If the project does not recompile after editing and saving, the issue lies in the watch functionality, so it may be related to the file system. For example, either network file system or soft links in the project can cause such issues.

If it recompiles, but the browser does not refresh, it may be a network issue, that is, `webpack-dev-server` asks the wrong host/port for the HMR information.

**Comment by geekduck** [comment]
Chrome console log shows: 
```
Access to XMLHttpRequest at 'http://192.168.0.5:8080/sockjs-node/info?t=1597821034692' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. localhost/:1
Failed to load resource: net::ERR_FAILED 192.168.0.5:8080/sockjs-node/info?t=1597821034692:1
[WDS] Disconnected! client?9214:172
```

I using VPN on macOS.
The VPN is blocking websocket access to 192.168.x.x.
HMR enabled after stopping VPN.
Thanks! Solved my issue.
