### ISSUE TITLE
In component builder, eslint is enabled by default and doesn't let me use a necessary escape character in <\/script>, calls it "unnecessary"

### ISSUE THREAD

**Issue by kamran-12** [vuejs/vue-cli#5913]
### Version
4.5.6

### Reproduction link
[https://pastebin.pl/view/0b08cc3d](https://pastebin.pl/view/0b08cc3d)

### Environment info
```
  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 80.0.1
    Safari: 14.0
  npmGlobalPackages:
    @vue/cli: 4.5.6
```

### Steps to reproduce
1. store the content of the pastebin as a "comment.vue" file
2. on terminal, go to the folder where the "comment.vue" file is stored, type "vue serve comment.vue"

### What is expected?
No errors

### What is actually happening?
This eslint error is shown: "error  Unnecessary escape character: \/                           no-useless-escape"

Removing the "unnecessary" escape character causes another error, as described here: https://github.com/vuejs/vue-loader/issues/506

---
I didn't enable eslint myself, and it is not used in my project. The bug here is the fact that eslint with wrong parameters was enabled by default. How can I reconfigure or remove eslint for the component builder?

**Comment by sodatea** [comment]
Because `vue serve` runs the global "instant prototyping" utility, which has eslint enabled by default. https://cli.vuejs.org/guide/prototyping.html#vue-serve Should use `yarn serve` or `npm run serve` instead.

I'm considering removing this functionality and aliasing it to the project-local command in the next major version, to avoid confusion.

As for the eslint rule complaint, maybe you can report to https://github.com/vuejs/eslint-plugin-vue/, and for now please use `// eslint-disable-line` as a workaround https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
