### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by wedog** [vuejs/vue-cli#606]
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

++++++++2+++++++++
11 10 2017 15:32:36.480:ERROR [plugin]: Error during loading "E:\work\mvue\node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
11 10 2017 15:32:40.092:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/

**Comment by wedog** [comment]
I don't know where is the location module ,so path is empty!
I solved it, i run 'npm run install' in 'phantomjs-prebuilt' module.

**Comment by posva** [comment]
Hey, the problem doesn't come from vue-cli, it comes from the template you used. I recommend you to ask for help on the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/). If it turns out there's a problem on the template, please create an issue, or even better, a pull request to fix it 🙂
