### ISSUE TITLE
can support react？

### ISSUE THREAD

**Issue by screetBloom** [vuejs/vue-cli#6153]
### What problem does this feature solve?
Want to know if vue cli can be used to develop react projects?

- I created a demo with create react app
- simply modified the webpack/babel configuration
- Run it with @vue/cli-service@4.x, and found that it worked fine

`http://localhost:8080/demo`

![image](https://user-images.githubusercontent.com/22092110/102565290-2161a500-4118-11eb-97ef-bb664516c51b.png)

<br>

### Reproduced Repo
[repo](https://github.com/screetBloom/Vue-CLI-React)

<br>

### What does the proposed API look like?
I use Vue CLI because it has a good plugin design

<br>

So I want to check if there are any problems with using react with Vue CLI

@sodatea 

<br>
<br>

**Comment by sodatea** [comment]
Theoretically, React can be supported. See https://github.com/miccycn/vue-cli-plugin-react

I don't know any issues about that though, because I don't develop React apps on a daily basis.
If you encounter any issues when using Vue CLI for React development, please open bug reports or feature requests in a more specific way.

**Comment by screetBloom** [comment]
got it，thx～
