### ISSUE TITLE
when will vue-cli support Typescript officially？

### ISSUE THREAD

**Issue by anymost** [vuejs/vue-cli#669]
hi，I knew Evan you @yyx990803 said that vue-cli will support Ts，so I follow when vue-cli will support Typescript officially？
#

**Comment by LinusBorg** [comment]
There's already some great user templates out there. so we won't tackle a new template until vue-cli 3.0 is done in order to  concentrate our limited resources on that. 3.0 will support typescript via presets directly.

Since 3.0 development is in its very eraly stages, that will be a couple weeks or rather, months away.

**Comment by anymost** [comment]
Actually, template is not the most difficultly to handle. when I want to use Typescript in Vue-cli, The most complex problem I have to face is config. There is too many config need to be modify, So I am looking forward to Vue-cli will Support Typescript as soon as possible

**Comment by LinusBorg** [comment]
> The most complex problem I have to face is config

In what way? I don't see too much work necessary:

* create `tsconfig.json`
* add `ts-loader` rule
* use `<script lang="ts">` in `.vue` files
* possibly install `ts-jest` and add a line to jest-config (if you test with jest).
* ... what else ?

**Comment by anymost** [comment]
Thanks a lot, I will try it

**Comment by forzeny** [comment]
m
