### ISSUE TITLE
Problem to create a project

### ISSUE THREAD

**Issue by andersonaguiar** [vuejs/vue-cli#794]
### Version
3.0.0-alpha.9

### Reproduction link
[https://d2ffutrenqvap3.cloudfront.net/items/0X3h1G1G381I163G1N3t/Image%202018-02-07%20at%202.50.42%20pm.png?v=a31218fa](https://d2ffutrenqvap3.cloudfront.net/items/0X3h1G1G381I163G1N3t/Image%202018-02-07%20at%202.50.42%20pm.png?v=a31218fa)

### Steps to reproduce
vue init webpack common

(enter till the end)

### What is expected?
Generate the project

### What is actually happening?
vue-cli · [.babelrc] Missing helper: "if_or"

**Comment by yyx990803** [comment]
Can't reproduce. I used the exact same prompt options and it works as expected. This seems quite weird because [the helper](https://github.com/vuejs-templates/webpack/blob/develop/meta.js#L22) is obviously defined and it's been there for over a month.

Likely a cache related issue, looks like your network fetched some outdated files.

**Comment by andersonaguiar** [comment]
Solved.

https://github.com/yarnpkg/yarn/issues/1321

I was trying to install vue-cli via yarn, but have been unsuccessful.

**Comment by vvo** [comment]
@andersonaguiar does it means vue-cli can't be installed via yarn? Installation for me is "successful" (minor some errors). But then vue init fails at the step you said.

**Comment by SneakyMax** [comment]
Yeah, same deal here, it seems that `vue-cli` can't be installed via Yarn. Uninstalling it and reinstalling via npm works fine.

**Comment by qwfy5287** [comment]
the same error, use yarn global add @vue/cli

use npm install -g @vue/cli is ok
