### ISSUE TITLE
Do we have plan for webpack4?

### ISSUE THREAD

**Issue by thangman22** [vuejs/vue-cli#836]
### What problem does this feature solve?
Webpack 4 beta is release and probably release in same time with vue-cli 3.0. Do we should upgrade Webpack to Webpack 4? 

### What does the proposed API look like?
We have to remove CommonsChunkPlugin and change to optimization.splitChunks for breaking change

**Comment by thangman22** [comment]
Should we try to upgrade vue-cli 3.0 to webpack4 before they release?. When webpack4 release we will no need to change again

**Comment by LinusBorg** [comment]
I don't think so. Webpack is still In alpha, and we don't want to develop cli3 on an unstable software - that would mean we develop against a moving target. 

Since we are closely monitoring the development and the webpack team is keeping us informed about things we will have to change, it will be quite easy to upgrade after webpack4 is released. 

Adding to that, we probably want to wait a few weeks until webpack4 has fixed any immediate bugs, which *will* emerge after such a big release.

**Comment by yuu2lee4** [comment]
webpack4 has released beta2

**Comment by LinusBorg** [comment]
We already use babel7

**Comment by cannap** [comment]
https://github.com/webpack/webpack/releases/tag/v4.0.0 💃

**Comment by LinusBorg** [comment]
We noticed. We will however take out time to include this, for one to test it, and also because the docs for 4 are not existant yet.

**Comment by LinusBorg** [comment]
Note: Since we use webpack-chain to build the core's webpack config, we should check out if there are any compatibility issues with webpack 4.

So far I'm aware of some new config options, which are not a problem. Changes in Syntax (if those exist!) for existing things might require some workarounds until webpack-chain has catched up.

**Comment by thangman22** [comment]
Let's me try to update in my brach will update you soon

**Comment by thangman22** [comment]
html-webpack-plugin still have problem with webpack 4

**Comment by yyx990803** [comment]
Closing since the answer is yes - will open a separate tracking issue when we try to finalize it.

**Comment by marco-carvalho** [comment]
i think some loaders are having problems with webpack 4, like html-webpack-plugin and [pug-loader](https://github.com/pugjs/pug-loader/issues/107)
