### ISSUE TITLE
Vue JSX not 100% supported in Babel 7

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#885]
### Version
3.0.0-alpha.13

### Reproduction link
[https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11](https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11)

### Steps to reproduce
Try to use `v-model` within JSX.

### What is expected?
It works.

### What is actually happening?
A compile-time error, as [described here](https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11).

---
If fixing the errors is easy, we can do that (haven't looked too deeply into it). If not, we may want to downgrade to Babel 6 in Vue CLI 3 for now.

**Comment by LinusBorg** [comment]
I think https://github.com/nickmessing/babel-plugin-jsx-v-model/issues/11 is the more serios version of this issue, but it should be solvable as demonstarted by the fixed fork posted in that issue by someone.

I'll add the `upstream` label since this can't be fixed in vue-cli itself, but has to be fixed in its dependencies.

**Comment by yyx990803** [comment]
I've updated `babel-plugin-transform-vue-jsx` for Babel 7 and disabled the ones that are not Babel 7 compatible yet in 389ea864b09b52b46c3704e265e7fb6f4c2d1a42

We'll re-enable them when they are ready.
