### ISSUE TITLE
These relative modules were not found

### ISSUE THREAD

**Issue by Pradeep0610** [vuejs/vue-cli#888]
* ../../../node_modules/bootstrap-sass/assets/javascripts/bootstrap.min in ./resources/assets/js/app.js
* ../../../node_modules/flexslider/jquery.flexslider-min in ./resources/assets/js/app.js
* ./easing in ./resources/assets/js/app.js
* ./minicart.min in ./resources/assets/js/app.js
* ./move-top in ./resources/assets/js/app.js
* ./site in ./resources/assets/js/app.js

**Comment by matrey** [comment]
_(adding a note because search engines still brought me here in 2019)_

I had the same kind of error after cloning a vuejs project on a new machine. 
Turns out `npm install` did not install development packages (maybe it assumed it was a production environment ; I'm using Linux Mint). I had to run an extra `npm install --dev` to get them, and all "relative modules were not found" errors disappeared.
