### ISSUE TITLE
Add specific .editorconfig file for each specific style linting

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vue-cli#905]
### What problem does this feature solve?
This feature will configure autocomplete to a specific style in any IDE that support .editorconfig file. For example when choosing linter to use AirBnB or StandardJS style, it will generate editorconfig with that specific style. 

> Just info : content in editorconfig file is universal and can be applied to any IDE. 

### What does the proposed API look like?
Prompt
```
Create editorconfig? Y/n
```
Or just create it without prompting.

**Comment by psg2** [comment]
Could I start working on this feature?

**Comment by kazupon** [comment]
Sure! 🙂

**Comment by psg2** [comment]
Just to be clear about the proposal.

During the prompt both on the create command and on the invoke with cli-plugin-eslint, it should ask if the user wants to create an editorconfig file if the Airbnb or the Standard option was chosen?

And the config files should be the ones contained in the repositories:
- [Airbnb](https://github.com/airbnb/javascript/blob/master/.editorconfig)
- [Standard](https://github.com/standard/standard/blob/master/.editorconfig)

Or is it best to create the editorconfig file without prompting?

**Comment by hsxfjames** [comment]
I vote for create without prompting, so that peoples do not have to worry about too much options.

**Comment by psg2** [comment]
What should happen during invoke if the user already has an editorconfig file?

**Comment by elevatebart** [comment]
I would love to keep consistency with the choosen linters. 
For instance, if I choose eslint preset AirBnB, I keep AirBnB for the .editorconfig.
And since @vue/cli supports prettier preset for eslint we should try to implement it as well.

Regarding the prompt, @psg2 I would use the linter if there is one and ask for a preset if not.

What do you think ?

**Comment by daekano** [comment]
Also might be prudent to think about what happens when TypeScript is enabled. You can use either ESLint or TSLint on TypeScript projects. There are AirBnb presets for both TSLint and ESLint too. Do we require some kind of abstraction above ESLint and TSLint with some kind of negotiator behind the scenes?

**Comment by psg2** [comment]
@elevatebart I'm sorry, but I didn't understand what you meant by "And since supports prettier preset for eslint we should try to implement it as well.".

Could you explain one more time?

@daekano I think there's no adjustment considering Typescript. Because the editorconfig from Airbnb and standard would remain the same. And the other linting options doesn't have default editorconfig files. 
But as for the cli, maybe there should be options for TSLint + Airbnb, TSLint + Standard, etc... Instead of just default TSLint and various ESLint options when Typescript is chosen.

**Comment by psg2** [comment]
@elevatebart I understand that. But eslint-config-prettier doesn't provide an editorconfig file. So if the users choose eslint + prettier as the linter option, it should not generate an editorconfig file and would stay as it is today. 
Or should we declare an editorconfig file for that option?

**Comment by elevatebart** [comment]
Indeed, my bad, the whole purpose of prettier is specifically to avoid the need of a config file.

**Comment by DrSensor** [comment]
> I hope this can be helpfull

- For integrating `.editorconfig` with `tslint`, 
using [tsfmt](https://github.com/vvakame/typescript-formatter) maybe can help. The trick is set `--no-vscode` and `--no-tsfmt`

- For combining TSLint with another ESLint config (AirBnB or Standard),
there is an issue that just opened #1021

**Comment by psg2** [comment]
I'm sorry that after so long I haven't made any progress on this issue.
I didn't manage my time properly and got caught up on work.
Can I still work on this or is anyone else interested?

**Comment by LinusBorg** [comment]
Feel free to go ahead  :)
