### ISSUE TITLE
vue-cli-service build --dest

### ISSUE THREAD

**Issue by Caravus** [vuejs/vue-cli#909]
### Version
3.0.0-beta.2

### Steps to reproduce
Run
./node_modules/.bin/vue-cli-service build --dest static

### What is expected?
All files in `static` dir

### What is actually happening?
`public/favicon.ico` copied to default folder (`dist`)

---
Trying to move compiled files to another dir in my fresh project, but `favicon.ico` appears in `./dist`.

P.S.: So, what link should i provide?

**Comment by LinusBorg** [comment]
Seems we have to overwrite options.outPutDir here

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/index.js#L60-L69

```diff
    if (args.dest) {
+      cons path = path: path.resolve(
+        api.service.context,
+        args.dest
+      )
+      options.outPutDir = path
      api.configureWebpack({
         output: path
-        output: {
-          path: path.resolve(
-            api.service.context,
-            args.dest
          )
        }
      })
    }
```
...because the copy webpack plugin uses `options.outputDir` to set the directory to copy to when the webpack config is resolved later in the build script:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/app.js#L151
