### ISSUE TITLE
Async Webcomponents can not be loaded from other directory than ./

### ISSUE THREAD

**Issue by batje** [vuejs/vue-cli#949]
### Version
3.0.0-beta.5

### Reproduction link
[https://github.com/batje/asyncwcpath](https://github.com/batje/asyncwcpath)

### Steps to reproduce
- Compile at least 2 components with  --target wc-async
- copy dist/demo.html to src/demo.html
- in src/demo.html change the path to your component.js by adding ../dist/
- load src/demo.html in your browser. 
- component.js will load, but component.1.js will fail

### What is expected?
component.1.js should be loaded from a path relative to component.js, not relative to the demo.html file.

### What is actually happening?
This line
https://github.com/vuejs/vue-cli/blob/57ce32a7106ee8f66d869b5f7bb39d1957d4258e/packages/%40vue/cli-service/lib/commands/build/resolveWcConfig.js#L72

sets publicpath to './' which causes webpack to look for the second file relative to the html file, not the .js file.

---
Better would be to 

- default to './'
- add a new command-prompt option called 'libpath' that you can set to a path like the examples in the webpack documentation
- if 'libpath' equals 'RUNTIME' do not fill in publicpath and allow setting the variable at runtime. eg:   __webpack_public_path__ = myRuntimePublicPath

Documentation for this option is here:
https://webpack.js.org/configuration/output/#output-publicpath

**Comment by batje** [comment]
Awesome

**Comment by batje** [comment]
Not sure if I understand correctly. The issue I describe is fixed. 
Basically, webcomponents run completely independent. You only need to include vue, and the webcomponents js file. After that, there is no js code in your html anymore, only you custom `<component>` tags.

The issue was, you could not do that with 2 vue based webcomponents on the same page. Now you can.

**Comment by xavsio4** [comment]
Well, still that is what I exactly did, the files are generated in the "..frontend/web/vuejs/" folder in a remote php project . The calling page in the root of that project has the vuejs and main component called, in my case, app-vue.min.js is the main component. In my webpage i'm using the tags (just as it is done on the demo.html file) and in the console i get this error "GET http://localhost/yiivue/frontend/web/app-vue.3.min.js net::ERR_ABORTED 404 (Not Found)" so the components are not loaded with the path relative to the main component which is called in "http://localhost/yiivue/frontend/web/vuejs/" but relative to the calling webpage. Now, if I move the components files where the calling page is, everything works fine. In that case, the main generated file is still in the folder "/vuejs"  but the file components are in the root folder along with the calling page. I've tried to force that with a vue.config.js file by using this piece of code`module.exports = {
    baseUrl: '/vuejs/',
  };`
And run the build command again, but I can't see no changes. Surely, I'm doing something wrong but can't figure out what (All is done on Chrome).

**Comment by xavsio4** [comment]
Ok, then what I was thinking about might then not be possible. In the documentation I read that when you have a large app with a lot of components you could use wc-async to split those components (foo-1, foo2, foo3, ....) and that only the component which is going to be used is going to be loaded on the page. Also I understood (badly it seems) that you only have to load the main vue component (which calls other components) and you don't have to link all generated js files in your page (and that is working if all files, including the page, are in the same folder. This is my "hub" component `<template>
  <div id="app">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
    <ArticleList></ArticleList>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import ArticleList from './components/ArticleList.vue'

export default {
  name: 'app',
  components: {
    HelloWorld,
    ArticleList
  }
}
</script>` 

and so the wc-async generates (with my command) app-vue.js, app-vue.1.js, app-vue.2.js, etc...
but i only link app-vue.js in the page. just like the demo one `<meta charset="utf-8">
<title>app-vue demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="./app-vue.js"></script>
<app-vue-article-list></app-vue-article-list>
<app-vue-hello-world></app-vue-hello-world>`

What i did wanted is something like this `<meta charset="utf-8">
<title>app-vue demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="**vuejs/app-vue.js**"></script>

<app-vue-article-list></app-vue-article-list>

<app-vue-hello-world></app-vue-hello-world>` from a page outside the generated js folder. But that won't work because there is not path for the components app-vue.1 and so on. That would have been nice, for example, to have a generation where demo.html is not in the same folder as the generated components. But perhaps I handle this problem from the wrong side.

**Comment by batje** [comment]
You dont need a hub component, the compile statement compiles all components in the components folder into your dist/ folder and creates 1 entry .js file

`vue-cli-service build --target wc-async 'src/components/*.vue' --name=mycomponents`

Now there will be 1 js file called [dist/mycomponents.js](url) Include that file, and you have access to all your components like `<mycomponents-name1>` etc. No hub needed.

**Comment by bjunc** [comment]
Is there a way to [explicitly set the public path](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/setPublicPath.js)?  This "fix" makes a few assumptions that the file will end with `.js`, and that the async files will be relative to the current script.  This does not work for our use-case; which is to create a proxy to web components (a la Docker versioning).

For instance:

`https://libs.example.com/wc:latest` would proxy/redirect to `https://some-cdn.com/webcomponents/v1.23.4/wc.min.js`

Under the current config, this will break. A workaround is to do something like this:

`https://libs.example.com/wc/latest/lib.js`

This is pretty ugly, IMO. It'd be better to be able to have an escape hatch to explicitly set the public path.
